# 결과: 급변 구간 과소예측 — 손실함수/후처리 개선 시도 및 구조적 한계 확정

작성일: 2026-09-20
상위 문서: `결과_TaskT_변동성예측_최종.md`(100종목 검증 정본) / `CLAUDE.md`
목적: 100종목 pooled 하이브리드(GARCH+Transformer) 변동성 예측 모델이 실측 상위20%
(급변) 구간에서 보이는 심한 과소예측 문제를, 재학습 가능한 세 가지 서로 다른 메커니즘
(가중 MSE·isotonic 후처리·pinball/quantile loss)으로 해결 시도한 전체 과정과 최종 결론을
기록한다. 전 과정은 fold3(train=2020-01-01~2024-10-07, val=2024-10-08~2025-09-25) val만
사용했고 **test(2025-09-26~오늘)는 어떤 실험에서도 평가하지 않았다.**

---

## [1] 문제 발견

100종목 pooled 하이브리드 모델(baseline, 15피처)의 val 예측을 실측값 상위20%
(quantile 기준, n=4,760)와 하위80%(n=19,040)로 나눠 평가한 결과:

| 구간 | RMSE | MAE |
|---|---|---|
| 상위20% | 3.9636 | 3.0028 |
| 하위80% | 1.2115 | 0.9954 |

하위80%(평상 구간)에서는 이미 GARCH(1,1)·SMA20 baseline을 둘 다 이기고 있었으나, 상위20%
(급변 구간)의 오차가 압도적으로 커서 전체 집계 게이트(SMA20·Parkinson-SMA20 대비)가
깨지는 원인이 여기 있음을 확인했다.

> ⚠️ **2026-09-27 정정**: 위 "전체 집계 게이트가 깨진다"는 전제는 운영 파이프라인의 게이트 집계
> 버그(하이브리드는 pooled RMSE, baseline은 종목별 RMSE 평균으로 비대칭 비교) 때문에 생긴 착시였다.
> 같은 방식으로 비교하면 이 baseline 모델은 전체 게이트를 이미 통과한다. 급변 구간 과소예측 자체는
> 실재하지만 "게이트 실패의 원인"은 아니었다 — 아래 [9] 참고.

### 세부 구간 분해

`|수익률| >= 2x 직전60일평균`을 "급변일"로 정의하고(결과_변동성_조기경보_검증.md의 "국면
진입 첫날" 라벨링 로직 재사용 — 그 문서의 GARCH σ 계산 버그는 recall/precision 수치에만
영향을 줬을 뿐 이 라벨 정의 자체와는 무관), 상위20%를 4개 그룹으로 재분해했다:

| 그룹 | 정의 | n | RMSE | MAE | bias(pred-actual) |
|---|---|---|---|---|---|
| ①진짜급변일 | 상위20% ∩ 급변일 | 2,666 | 5.0659 | 4.1832 | — |
| ②급변일 미달 | 상위20% ∩ ~급변일 | 2,094 | 1.7429 | 1.4998 | −1.4841 |
| ③하위80% | ~상위20% | 19,040 | 1.2115 | 0.9954 | — |
| ④지속중 | ①의 부분집합, "국면 진입 첫날"이 아닌 날(N=5 고립 기준) | 1,418 | 5.0997 | 4.1476 | **−4.1476(=−MAE, 사실상 전 샘플 과소예측)** |
| (참고)첫날 | ①의 부분집합, 국면 진입 첫날 | 1,248 | 5.0271 | 4.2237 | **−4.2237(=−MAE)** |

**핵심 발견**: 첫날/지속중 둘 다 bias가 MAE와 부호만 반대로 정확히 일치 — 사실상 전
샘플이 예외 없이 과소예측이다. GARCH σ가 이미 크게 반영된 "지속중" 구간에서도 이 편향이
전혀 완화되지 않았다(오히려 RMSE가 첫날보다 근소하게 더 나쁨: 5.0997 vs 5.0271).

### 사전 진단(재학습 없이) — "고칠 수 있는 결함"인지 확인

- **GARCH 단독 vs 하이브리드(④지속중)**: GARCH 단독 RMSE=4.3432(bias=−3.2637)로 하이브리드
  (RMSE=5.0997, bias=−4.1476)**보다 오히려 낫다** — 하이브리드가 자신의 입력 피처 중 하나인
  GARCH σ 단독보다도 이 구간에서 못 맞힌다는 뜻.
- **Spearman 순위상관**: ④지속중 ρ=0.5542, ③하위80% ρ=0.1732, 첫날 ρ=0.5956 — **지속중
  구간의 순위상관이 하위80%보다 오히려 3배 이상 높다.** 모델이 "더 클지 덜 클지"는 꽤 잘
  구분하지만 절대 레벨을 체계적으로 낮게 찍는다는 뜻.
- **예측값 분포 겹침**: ④지속중 예측값 중 ③하위80% IQR 안에 드는 비율 46.3%(<70%) —
  "모델 출력이 두 상황을 구분 못 한다"는 가설은 기각. 분포는 실제로 상당히 갈라져 있음
  (median 1.80 vs 2.26).

→ 종합: "정보 자체가 없다"보다는 "정보는 있는데 레벨이 체계적으로 낮게 나온다"는 진단이
섰고, 이는 후처리/손실함수로 고칠 수 있는 결함처럼 보였다.

---

## [2] 시도 1 — 가중 MSE (그룹 단위, 대칭 손실)

`loss = mean(weight_i x (pred_i-target_i)^2)`, 가중치는 train y 분포 상위20%(quantile)
초과 샘플에만 적용, W=1.5/2.0/3.0.

| variant | 상위20% RMSE | 하위80% RMSE | 하위80% beats SMA20 |
|---|---|---|---|
| baseline | 3.9636 | 1.2115 | True |
| W=1.5 | 3.7476 | 1.4060 | **False** |
| W=2.0 | 3.5703 | 1.5892 | False |
| W=3.0 | 3.3676 | 1.8413 | False |

W를 올릴수록 상위20%는 꾸준히 개선되지만 하위80%는 꾸준히 악화 — **W=1.5부터 이미 SMA20
게이트가 깨짐.**

가중 대상을 "상위20% 분위수 전체"에서 "진짜 급변일(2x기준, n=2,666)"로 좁혀 재시도:

| variant | ①진짜급변일 RMSE | ③하위80% RMSE | ③beats SMA20 |
|---|---|---|---|
| baseline | 5.0659 | 1.2115 | True |
| W=1.5 | 4.8703 | 1.3670 | **False** |
| W=2.0 | 4.6894 | 1.5318 | False |
| W=3.0 | 4.3817 | 1.8277 | False |

가중 대상을 좁히니 하위80% 악화폭은 실제로 줄었지만(같은 W에서 1.4060→1.3670 등),
**SMA20 게이트는 여전히 W=1.5부터 깨짐** — "①개선 + ③게이트 유지"를 동시에 만족하는
W 없음.

---

## [3] 시도 2 — Isotonic Regression (전역 후처리)

하이브리드 예측값을 입력, 실측값을 타겟으로 val 전체(n=23,800, 서브그룹 구분 없음)에
isotonic regression을 학습·적용.

| 그룹 | baseline RMSE | 보정후 RMSE | GARCH RMSE |
|---|---|---|---|
| ①급변일 | 5.0659 | 5.0546 | 4.4608 |
| ③하위80% | 1.2115 | 1.2109 | 1.8350 |
| ④지속중 | 5.0997 | **5.0769** | 4.3432 |

③게이트는 유지됐으나(GARCH·SMA20 둘 다 이김), **④의 GARCH 대비 격차는 +0.7565→+0.7337로
겨우 3% 축소** — 사실상 무효과. val 전체로 학습하다 보니 80%를 차지하는 평상 구간에
보정 함수가 지배되고, 희소한 상단 꼬리(급변 구간)에서는 계단 함수가 충분히 올라가지
못한 것으로 해석된다.

---

## [4] 시도 3 — Pinball(Quantile) Loss (샘플 단위, 비대칭 손실)

`loss_i = max(tau*(y_i-pred_i), (tau-1)*(y_i-pred_i))`, tau=0.6/0.7/0.8. train/val 둘 다
같은 tau의 pinball loss로 학습·모델선택(plain MSE가 아니라 pinball loss 자체로 조기종료
기준을 통일 — 모델이 애초에 tau번째 조건부 분위수를 맞히도록 최적화되므로).

| variant | ① | ② | ③ | ④ | ③beats GARCH | ③beats SMA20 |
|---|---|---|---|---|---|---|
| baseline | 5.0659 | 1.7429 | 1.2115 | 5.0997 | True | True |
| tau=0.6 | 5.2446 | 1.9589 | **1.0830** | 5.3050 | True | True |
| tau=0.7 | 4.6623 | 1.3675 | 1.5598 | 4.6672 | True | **False** |
| tau=0.8 | 4.0693 | 1.0893 | 2.1351 | **4.0444** | **False** | False |

④지속중 vs GARCH 단독(RMSE 4.3432) 격차(baseline +0.7565 기준):

| tau | 격차 | 축소율 | ④에서 GARCH를 이김 | ③게이트 |
|---|---|---|---|---|
| 0.6 | +0.9618 | −27.1%(악화) | No | 유지 |
| 0.7 | +0.3239 | 57.2% | No | SMA20 깨짐 |
| 0.8 | **−0.2989** | 60.5% | **Yes** | GARCH·SMA20 둘 다 깨짐 |

**tau=0.8은 세 시도를 통틀어 유일하게 ④에서 GARCH 단독을 실제로 이겼다**(4.0444 vs
4.3432). 그러나 ③이 완전히 무너진다(RMSE 1.2115→2.1351, +76%, GARCH·SMA20 둘 다 짐).
tau=0.6은 반대 방향 트레이드오프를 보였다 — ③은 오히려 개선(1.0830)됐지만 ④는 baseline
보다도 악화(격차가 -27% 즉 더 벌어짐).

세 tau 모두 "④ 50% 이상 축소 + ③게이트 유지"를 동시에 만족하지 못했다.

---

## [5] 최종 결론 — 구조적 한계 확정

**메커니즘이 근본적으로 다른 세 가지 방법**(그룹 단위 대칭 재가중, 전역 후처리 재보정,
샘플 단위 비대칭 손실)**이 전부 동일한 트레이드오프에 부딪혔다**: 급변 구간(특히 GARCH
신호가 이미 반영된 "지속중" 구간까지 포함)의 예측력을 올리려 하면 평상 구간(하위80%,
전체 표본의 80%를 차지하며 이미 GARCH·SMA20을 이기고 있던 구간)의 성능이 그만큼, 혹은
그 이상으로 희생된다. 가장 극단적으로 밀어붙인 pinball tau=0.8조차 급변 구간에서 GARCH를
이기는 대가로 평상 구간 게이트를 완전히 무너뜨렸다.

**해석**: 사전 진단(GARCH 단독보다 못함, 순위상관은 살아있음, 분포는 부분적으로만 겹침)이
가리켰던 "고칠 수 있는 결함"이라는 판단 자체는 틀리지 않았다 — 실제로 세 방법 모두 급변
구간 성능을 상당 폭 끌어올릴 수 있었다(pinball tau=0.8: RMSE 5.0997→4.0444, 21% 개선).
문제는 **"고칠 수 있느냐"가 아니라 "평상 구간을 희생하지 않고 고칠 수 있느냐"였고, 이번
세 시도 결과로는 후자가 성립하지 않는다.** 100종목을 하나의 파라미터 공유 pooled 모델로
묶어 학습하는 현재 구조에서는, 단일 모델의 표현력이 "평상시 정확도"와 "급변 시 정확도"를
한꺼번에 만족시킬 만큼 충분하지 않거나, 두 목표가 학습 과정에서 근본적으로 경쟁 관계에
있는 것으로 보인다.

**최종 결론**: 급변 구간(상위20%, 특히 지속중 구간) 개선 시도는 이번 세 방법(가중 MSE·
isotonic·pinball loss)의 범위 내에서는 **평상 구간 게이트를 유지한 채로는 해결되지
않는 구조적 한계**로 결론짓는다. 현재 배포 게이트 기준(GARCH·SMA20·Parkinson-SMA20 셋
다 이겨야 통과)과 급변 구간 정확도는 이 pooled 모델 구조 안에서 양립하지 않는다.

---

## [6] 실무적 함의 및 후속 검토 후보 (결정 아님, 사람 판단 대기)

- **현재 baseline(15피처, MSE)을 그대로 유지**하는 것이 여전히 최선이다 — 세 시도 모두
  baseline보다 나은 후보를 만들어내지 못했다.
- 급변 구간에서 이 모델의 예측(특히 `garch_sigma` 자체나 `is_early_warning` 플래그)은
  **참고용으로만 취급**하고, 실제 의사결정에서는 과소예측 경향(특히 지속중 구간에서도
  거의 100% 과소예측)을 감안해야 한다 — `model_predictions`를 소비하는 쪽에 이 한계를
  명시적으로 알릴 필요가 있다.
- 후속으로 고려할 수 있는(이번 세션에서 결정하지 않은) 방향:
  - **종목별/구간별 별도 모델**(pooled 단일 모델이 아니라 급변 구간 전용 게이팅 모델을
    별도로 두는 앙상블 구조) — 다만 이는 현재 아키텍처를 벗어나는 훨씬 큰 트랙이다.
  - **피처 자체 재검토**: 하이브리드가 GARCH σ보다도 못한 이유(스케일링, 다른 피처와의
    상호작용에 의한 신호 희석 등)를 원인 규명하는 방향 — 이번 세션에서 시도하지 않았다.
  - 위 두 방향 모두 이 문서의 범위를 넘는 별도 검토가 필요하며, 진행 여부는 사람이
    결정한다.

---

## [7] 추가 시도: 회귀 예측값 재활용 탐지

[5]의 "구조적 한계" 확정 이후, 회귀(레벨 맞히기)를 포기하고 이진분류(급변일 탐지)로 문제를
재정의할 수 있는지 검토했다. 3단계(새 BCE 모델 학습)로 바로 가기 전에, **기존에 이미 학습된
예측값을 재학습 없이 탐지기로 재활용할 수 있는지**부터 확인하는 것이 1~2단계였다.

라벨: `|수익률| >= 2x 직전60일평균`("급변일", [1]과 동일 정의). fold3 val 구간
(n=23,800, 급변일 비율=0.1233, 이 값이 "무작위 baseline"의 PR-AUC 기준선)에서 baseline
(15피처, MSE), tau=0.8 pinball(급변 지속구간에서 유일하게 GARCH를 이겼던 모델, [4] 참고),
GARCH sigma 단독 — 셋의 predicted_volatility를 "값이 클수록 급변일일 것 같다"는 연속
점수로 취급해 PR-AUC(average precision)를 계산했다.

| 모델 | PR-AUC | 기준선(0.1233) 대비 배율 | 확실히 우수(>=2x)? |
|---|---|---|---|
| baseline(15피처, MSE) | 0.1421 | 1.15x | ❌ |
| tau=0.8 pinball | 0.1463 | 1.19x | ❌ |
| GARCH 단독 | 0.1356 | 1.10x | ❌ |

임계값별 precision/recall(상위 n%를 "양성 예측"으로 플래그):

| 모델 | 상위30% | 상위20% | 상위10% |
|---|---|---|---|
| baseline | P=0.143 R=0.347 | P=0.151 R=0.245 | P=0.154 R=0.125 |
| tau=0.8 pinball | P=0.146 R=0.356 | P=0.153 R=0.249 | P=0.162 R=0.131 |
| GARCH 단독 | P=0.131 R=0.318 | P=0.132 R=0.214 | P=0.142 R=0.115 |

**결론: 셋 다 무작위 대비 확실한 우위가 없다**(전부 1.1~1.2배 수준, 판정 기준 2배에 크게
못 미침). tau=0.8 pinball이 셋 중 가장 낫지만(상위10% 기준 precision 0.162 — 무작위
0.123보다 소폭 높은 정도) 탐지기로 실전 재활용하기엔 부족하다. **회귀 예측값 재활용은
기각 — 이진분류(BCE) 모델을 새로 학습하는 방향(3단계)으로 전환한다.** 3단계는 이 문서
작성 시점 기준 사람 승인 대기 중이다.

참고로 이 결과는 `결과_변동성_조기경보_검증.md`가 가리키던 것과 **같은 규칙**(예측σ가
직전 60일 예측σ 평균의 1.5배를 초과하면 경보)을, GARCH 라벨링 버그 수정 후 다시 검증한
것과 같은 계열이다 — 그 문서의 1차 결과(recall 84.6%~91.3%)는 버그로 무효화됐고, 버그
수정 후 재검증에서 recall이 0.7%(우연 수준)로 무너졌다는 것이 `가격예측_변동성_공통.py`의
`_trailing_predicted_volatility_mean` 코드 주석에만 짧게 남아있었다 — 이번 PR-AUC
결과가 그 미문서화된 결론을 정량적으로 재확인해준다.

사용 스크립트: `가격예측/검증용/anomaly_detection_pr_auc_check.py`(유지 — highvol_regime_
diagnosis.py의 급변일 라벨링 함수에 의존하므로 그 파일도 함께 유지).

---

## [8] 사용된 스크립트 (전부 `가격예측/검증용/`, 재학습이 필요한 실험 전용)

- `ablation_feature_pruning.py` — fold3 baseline/variant A/B (참고: 이 문서와 별개 트랙)
- `loss_weighting_high_vol.py` — 가중 MSE 1차(상위20% 분위수 전체) — ⚠️ 결과 문서화 후 삭제(2026-09-20)
- `highvol_regime_diagnosis.py` — 첫날/지속중 라벨링 + RMSE/MAE 분해 — **유지**([7]의
  `anomaly_detection_pr_auc_check.py`가 여기 정의된 급변일 라벨링 함수를 계속 사용)
- `loss_weighting_bigmove_v2.py` — signed bias 확인 + 가중 MSE 2차(진짜 급변일만) — ⚠️ 삭제
- `highvol_diagnosis_v3.py` — GARCH 단독 비교 + Spearman 순위상관 — ⚠️ 삭제
- `pred_distribution_overlap_check.py` — 예측값 분포 겹침 진단(+히스토그램/박스플롯) — ⚠️ 삭제
- `isotonic_calibration_v1.py` — isotonic 후처리 보정 — ⚠️ 삭제
- `pinball_loss_sweep.py` — pinball/quantile loss 스윕(tau=0.6/0.7/0.8) — ⚠️ 삭제
- `anomaly_detection_pr_auc_check.py` — [7]의 PR-AUC 진단 — **유지**(다음 트랙인 이상탐지
  전환 검토로 이어지는 근거 스크립트)

⚠️ 표시된 5개 스크립트 + `가격예측/checkpoints/pred_dist_overlap_g4_vs_bottom80.png`는
이 문서로 결과가 완전히 문서화된 뒤 **2026-09-20 삭제됐다**(사람 승인) — 급변구간 손실함수
트랙(가중MSE/isotonic/pinball) 자체가 "구조적 한계"로 결론나 재사용 가치가 없다고 판단.
`highvol_regime_diagnosis.py`/`anomaly_detection_pr_auc_check.py`는 다음 트랙(이상탐지
전환 검토)이 계속 참조하므로 유지했다.

모두 fold3 val만 사용했고 test는 전혀 평가하지 않았다. `가격예측/train_common.py`에
`train_pooled_transformer_weighted`(가중 MSE)와 `train_pooled_transformer_pinball`
(pinball loss) 두 함수가 이 실험들을 위해 추가됐다 — 기존 `train_pooled_transformer`는
값 변경 없이 그대로 보존. 이 두 함수는 스크립트가 삭제된 뒤에도 **이 문서와의 코드-문서
정합성을 위해 그대로 유지**한다(사람 결정, 2026-09-20).

---

## [9] 게이트 집계 버그 수정 후 재검증 (2026-09-27)

**배경**: 2026-09-27 운영 게이트의 집계 비대칭 버그를 발견했다(CLAUDE.md "게이트 집계 버그" 절).
이 문서의 판정이 같은 비대칭에 오염됐는지 확인하려 했으나, [8]의 ⚠️ 스크립트 4개(가중 MSE 1·2차,
isotonic, pinball)는 **git에 한 번도 커밋되지 않은 채 삭제돼 코드 확인이 불가능**했다. 그래서
`train_common.py`에 남은 학습 함수 + `highvol_regime_diagnosis.py`의 그룹 라벨링 함수로 같은 실험을
재실행하고, 모든 그룹에서 하이브리드와 baseline을 **같은 행·같은 집계 방식**(pooled / 종목별 평균
두 가지 모두)으로 비교했다. 분할 경계가 당시와 약간 다르므로(train_end 2024-10-07→2024-10-10,
baseline 유효 행 23,737/23,800) 수치가 원 표와 소수점까지 같지는 않다. seed 42 단일, val만.

**원 판정의 집계 방식**: 원 표의 ③ GARCH RMSE(1.8350)가 이번 pooled 값(1.8238)과 근접하고 종목평균
값(1.8034)과는 멀어, 그룹별 비교는 **pooled끼리의 대칭 비교**였던 것으로 보인다 — 즉 그룹별 판정은
게이트 버그의 영향을 받지 않았다(영향을 받은 것은 [1]의 "전체 게이트가 깨진다"는 전제뿐).

**재검증 결과(종목별 RMSE 평균 — 운영 게이트와 같은 방식)**. baseline: 전체 GARCH/SMA20/Parkinson =
2.1450/2.0177/2.0013, ③ = 1.8034/1.2915/1.3560, ④ GARCH = 3.9786.

| variant | 전체 | ③하위80% | ①급변일 | ④지속중 | 전체 게이트 | ③ 게이트(G·S·P) | ① 개선 |
|---|---|---|---|---|---|---|---|
| baseline(MSE) | 1.9594 | 1.2182 | 4.6886 | 4.6436 | 통과 | 통과 | — |
| isotonic(val 적합, in-sample) | 1.9555 | 1.2011 | 4.6994 | 4.6539 | 통과 | 통과 | 아니오 |
| 가중(상위20%q) W=1.5/2.0/3.0 | 1.9746/2.0066/2.0704 | 1.3591/1.4968/1.7025 | 4.5157/4.3632/4.1417 | — | 통과/실패/실패 | 전부 실패 | 예 |
| 가중(급변일) **W=1.5** | 1.9671 | **1.2891** | 4.5960 | 4.5462 | 통과 | **통과(SMA20 대비 여유 0.0024)** | 예(−2.0%) |
| 가중(급변일) W=2.0/3.0 | 1.9901/2.0678 | 1.4320/1.6893 | 4.4187/4.1465 | — | 통과/실패 | 실패 | 예 |
| pinball τ=0.6/0.7/0.8 | 1.9651/2.0096/2.2161 | 1.1390/1.5052/2.0157 | 4.8151/4.3609/3.8182 | 4.7898/4.3005/**3.6912** | 통과/실패/실패 | 통과/실패/실패 | 아니오/예/예 |

pooled 집계로 봐도 게이트 통과/실패 패턴은 전 variant에서 동일했다.

**판정: 결론 유지 — 게이트 버그 수정 후에도 "구조적 한계" 결론은 실질적으로 불변.**
- 원 실행과 달리 **가중(급변일) W=1.5 하나가 "① 개선 + ③ 게이트 유지"를 형식상 동시 만족**했다
  (원 문서: ③ 1.3670으로 SMA20에 짐). 그러나 이는 게이트 버그와 무관한 실행 간 변동으로 보인다 —
  ③ 여유가 0.0024(0.2%)에 불과한데, 같은 설정 LSTM의 seed 간 ③ 변동폭은 0.065(1.2233~1.2879)로
  이보다 27배 크다. ① 개선도 −2.0%로 미미하고, ④에서는 여전히 GARCH에 진다(격차 0.665→0.568).
  **전체 RMSE는 오히려 baseline보다 나빠진다**(1.9594→1.9671). 단일 seed의 경계선 결과라 채택 근거가
  되지 못한다 — 여러 seed에서도 ③ 게이트를 유지하는지 확인되기 전까지는 "재검토 후보"로만 기록한다.
- pinball τ=0.8은 이번에도 ④에서 GARCH를 이기지만(3.6912 < 3.9786) ③·전체 게이트가 무너진다 —
  원 결론과 동일한 트레이드오프.

---

## [10] GARCH↔LSTM 국면 전환 블렌딩 — ❌ 종료, 구조적 한계로 확정 (2026-09-27)

[9] 이후 "급변일엔 GARCH, 평상일엔 LSTM"을 예측 시점에 쓸 수 있는 스위치로 고르는 블렌딩을 두 가지로
시도했다(운영 LSTM seed 42 val 예측 재사용, 새 학습 없음, val만, 그룹 정의는 [9]와 동일).

**사후 그룹별 기준선**(오라클 방향 가격 추정 %오차 RMSE): ①급변일은 GARCH 단독이 최선(4.37%, LSTM 4.93%),
③평상일은 LSTM 단독이 변동성 모델 중 최선(1.16%, GARCH 1.75%). 단 그룹은 실측으로 나눈 것이라 예측 시점엔
알 수 없다 — 이 격차를 실시간으로 잡으려면 신뢰할 만한 스위치가 필요하다.

**시도 1 — `garch_sigma`(예측 시점 GARCH σ) 임계값 스위치**(train 70/80/90분위): GARCH로 전환되는 비율이
①급변일 18~44% vs ③평상일 12~33%(배율 1.31~1.49x)로 거의 안 갈림. 전체 변동성 RMSE(종목평균)
2.0353~2.0804로 LSTM 단독(1.9643)보다 나쁘고 **셋 다 배포 게이트 실패**(SMA20·Parkinson에 짐). 임계값을
낮추면 ①이 좋아지는 만큼 ③(표본의 80%)이 더 나빠지는 동일한 트레이드오프.

**시도 2 — 15피처 GBM 급변일 분류기 확률 스위치**(PR-AUC 1.24x 모델, train 확률 70/80/90분위): 전환율이
①급변일 20~53% vs ③평상일 18~49%로 **배율 1.08~1.16x — 시도 1보다도 못 가른다.** 사전 정한 규칙대로
블렌딩 성능 평가는 생략(가르지 못하는 스위치로는 각 구간 최선에 다가갈 수 없음). 참고로 train 분위수
임계값에서 val 전환율이 명목치보다 크게 높다(70분위 → 48%) — val에서 확률 분포가 위로 이동.

**결론**: 지금 가진 신호(예측 시점 GARCH σ, 15피처 GBM)로는 급변일과 평상일을 실시간으로 가르는
"신뢰할 만한 국면 전환 스위치"를 만들 수 없다는 것이 두 번 확인됐다. [5]의 손실함수 3종, [7]·CLAUDE.md의
급변일 분류기(PR-AUC 1.1~1.24x)와 같은 근본 원인 — **현재 피처에는 다음날 급변 여부를 가르는 정보가
약하다.** GARCH·LSTM 블렌딩 방향은 여기서 종료하고, 급변 전문 모델 등 세 번째 시도로 넘어가지 않는다.
운영은 LSTM 단독 유지. 수치: `발표자료/blend_garch_lstm.csv`, `발표자료/price_estimate_by_regime.csv`.

---

## [11] LSTM 규제 완화 — ❌ 효과 없음, 트랙 최종 종료 (2026-09-27)

"규제가 예측을 평균 쪽으로 누른다"는 가설로 dropout·weight_decay를 낮춰 LSTM(seed 42, 운영과 같은 데이터·split)을
재학습했다. (0.3, 1e-4)는 운영 설정 그대로이며 게이트 1.9648을 재현했다.

| (dropout, wd) | 게이트 RMSE | 예측/실측 std | 예측 max | ① 가격 %오차 | ① 평균 편향 | ③ 가격 %오차 | ③ 게이트 |
|---|---|---|---|---|---|---|---|
| (0.3, 1e-4) 기존 | 1.9648 | 0.271 | 4.63 | 4.925% | −4.12 | 1.158% | 통과 |
| (0.15, 1e-4) | 1.9658 | 0.274 | 5.30 | 4.907% | −4.10 | 1.167% | 통과 |
| (0.15, 1e-5) | 1.9671 | 0.277 | 5.47 | 4.923% | −4.12 | 1.160% | 통과 |
| (0.1, 0) | 1.9686 | 0.275 | 5.34 | 4.921% | −4.11 | 1.163% | 통과 |

(① GARCH+오라클 4.366%, ③ baseline 종목평균 RMSE GARCH/SMA20/Parkinson = 1.804/1.292/1.356)

std 비율은 0.271→최대 0.277로 사실상 불변, ①의 과소예측 편향(−4.1%p)도 그대로, ① 개선은 최대 0.4%로 GARCH와의 격차
(약 0.55%p)를 전혀 좁히지 못했다. 네 조합 모두 게이트는 통과하지만 전체 RMSE는 기존이 가장 좋아 **채택 후보 없음, 운영
설정 유지.** 분산 붕괴는 규제 강도의 문제가 아니다.

**트랙 종합 결론(2026-09-27)**: 손실함수(가중 MSE 2종·isotonic·pinball), 아키텍처(Transformer·LSTM), 국면 전환 블렌딩
(garch_sigma·GBM 스위치), 규제 완화까지 — 모델·손실·후처리·스위치를 바꾼 모든 시도가 같은 벽(급변일 과소예측과
평상일 정확도의 트레이드오프, 분산 붕괴 약 27~33%)에 부딪혔다. 공통 원인은 **현재 입력 정보로는 다음날 급변 여부를
미리 가를 수 없다**는 것(급변일 분류 PR-AUC 1.1~1.24x). 이 트랙은 "구조적 한계"로 종료한다. 남은 유일한 다른 종류의
경로는 **새 정보(피처) 추가**이며, 그 첫 후보(`market_bigmove_ratio`, 전날 시장 급변 비율 — 최상위 10분위에서 다음날
급변 확률 1.56x)는 상관 진단까지만 했고 재학습 여부는 미결정이다(CLAUDE.md 참고).
