# 결과: Task E — 라벨링 실행 결과

작성일: 2026-08-30
상위 문서: `TASK_EF_라벨링_비교실험.md`(Task E 지시서) / `CLAUDE.md` D-1~D-3, D-8
목적: Task E 실행 결과(z 분포·라벨 분포·레짐 특성)의 상세 수치를 보관한다. `CLAUDE.md`에는
결론과 확정 사항만 요약하고 상세 표는 이 문서를 참조하도록 분리했다(2026-08-31).

---

## 실행 조건

| 항목 | 값 |
|---|---|
| 대상 종목 | 005930(삼성전자) — `constants.ACTIVE_TICKERS` |
| 기간 | `TRAIN_PERIOD_START`~`TRAIN_PERIOD_END` = 2023-08-23 ~ 2026-08-28 |
| 데이터 소스 | `daily_stock_prices`(종목 change_rate), `market_indicators`(KOSPI, `시장지표/feature_loader.py`의 `get_indicator_level_series()`로 레벨을 읽어 자체 등락률 계산) |
| 라벨 저장 | `daily_labels`(z_score만 저장, 라벨은 조회 시 파생) — 005930 x 윈도우 3종 = 4,902행, 2020-01-02~2026-08-28 전체 가격 이력 대상 계산 |
| split 비율 | `constants.SPLIT_RATIOS` = (0.70, 0.15, 0.15), 시계열 순서(셔플 없음) |
| 실제 분할 | train 513일(2023-08-23~2025-09-30) / val 109일(2025-10-01~2026-03-18) / test 111일(2026-03-19~2026-08-28) — 총 733 거래일 |
| 실행 스크립트 | `라벨/라벨_생성.py`(적재), `라벨/라벨_보고.py`(본 보고) |
| 실행 일자 | 2026-08-30 |

---

## 계산 방식

```
excess_return_t = 종목 change_rate_t − KOSPI change_rate_t
sigma_t(N)      = 직전 N거래일 excess_return 표준편차 (t 시점 미포함, shift(1) 후 rolling(N))
z_t(N)          = excess_return_t / sigma_t(N)
```

윈도우 N = 20 / 60 / 120 각각 계산해 `daily_labels`에 저장(PK에 `window_n` 포함).

**초기 N일 처리**: 행은 유지하고 `sigma`/`z_score`만 `NULL`로 저장했다(행을 아예 빼지 않음).

- `excess_return`은 lookback이 필요 없어 첫날부터 계산 가능하다 — 행을 통째로 빼면 이 값까지 함께 잃는다
- CLAUDE.md D-2가 이미 "초기 N일은 라벨 NULL"이라고 명시했다 — 존재하는 방침을 그대로 따른 것
- 전체 가격 이력(2020-01-02~)을 대상으로 계산해 `TRAIN_PERIOD_START`(2023-08-23) 시점엔 이미
  3년 넘는 버퍼가 쌓여 있다. 실측 결과 `TRAIN_PERIOD` 내에서는 윈도우 20/60/120 어느 것도
  NULL이 0건이었다(아래 [1] "유효 733건"이 세 윈도우 모두 동일한 것으로 확인) — 학습에 실제로
  쓰이는 구간에서는 이 NULL 처리가 사실상 영향을 주지 않는다

---

## [1] z 분포 — 윈도우 N별 기술통계

| N | count | mean | std | min | 25% | 50%(중앙값) | 75% | max |
|---|---|---|---|---|---|---|---|---|
| 20 | 733 | 0.055782 | 1.158076 | -4.177868 | -0.645621 | -0.057088 | 0.626276 | 7.208955 |
| 60 | 733 | 0.041308 | 1.095216 | -3.446789 | -0.654516 | -0.060169 | 0.622054 | 6.708689 |
| 120 | 733 | 0.044180 | 1.110671 | -3.636058 | -0.660908 | -0.058083 | 0.625193 | 6.201568 |

세 윈도우 모두 거의 동일한 분포(평균 0에 근접, 표준편차 ~1.1, 약한 우측 꼬리) — 윈도우 선택이
z 분포 형태에 큰 영향을 주지 않는다.

### 히스토그램 (구간별 건수/비율)

| 구간 | N=20 | N=60 | N=120 |
|---|---|---|---|
| < -2 | 10 (1.4%) | 12 (1.6%) | 11 (1.5%) |
| -2 ~ -1.5 | 25 (3.4%) | 21 (2.9%) | 22 (3.0%) |
| -1.5 ~ -1 | 67 (9.1%) | 69 (9.4%) | 72 (9.8%) |
| -1 ~ -0.5 | 120 (16.4%) | 127 (17.3%) | 124 (16.9%) |
| -0.5 ~ 0 | 165 (22.5%) | 158 (21.6%) | 158 (21.6%) |
| 0 ~ 0.5 | 136 (18.6%) | 135 (18.4%) | 130 (17.7%) |
| 0.5 ~ 1 | 96 (13.1%) | 97 (13.2%) | 98 (13.4%) |
| 1 ~ 1.5 | 60 (8.2%) | 59 (8.0%) | 60 (8.2%) |
| 1.5 ~ 2 | 20 (2.7%) | 24 (3.3%) | 22 (3.0%) |
| > 2 | 34 (4.6%) | 31 (4.2%) | 36 (4.9%) |

---

## [2] 라벨 분포 — 임계값 후보 x 윈도우 N 교차 (TRAIN_PERIOD 전체, 733건)

### 방향 5-class (z ±0.5 / ±1.5)

| N | -2 | -1 | 0 | +1 | +2 |
|---|---|---|---|---|---|
| 20 | 35 (4.8%) | 187 (25.5%) | 301 (41.1%) | 156 (21.3%) | 54 (7.4%) |
| 60 | 33 (4.5%) | 196 (26.7%) | 293 (40.0%) | 156 (21.3%) | 55 (7.5%) |
| 120 | 33 (4.5%) | 196 (26.7%) | 288 (39.3%) | 158 (21.6%) | 58 (7.9%) |

### 방향 3-class (z ±0.5)

| N | -1 | 0 | +1 |
|---|---|---|---|
| 20 | 222 (30.3%) | 301 (41.1%) | 210 (28.6%) |
| 60 | 229 (31.2%) | 293 (40.0%) | 211 (28.8%) |
| 120 | 229 (31.2%) | 288 (39.3%) | 216 (29.5%) |

### 변동성 2-class — 후보 3종 (고변동 = \|z\| > 임계값)

| N | \|z\|>0.5 정상/고변동 | \|z\|>1.0 정상/고변동 | \|z\|>1.5 정상/고변동 |
|---|---|---|---|
| 20 | 301(41.1%) / 432(58.9%) | 517(70.5%) / 216(29.5%) | 644(87.9%) / 89(12.1%) |
| 60 | 293(40.0%) / 440(60.0%) | 517(70.5%) / 216(29.5%) | 645(88.0%) / 88(12.0%) |
| 120 | 288(39.3%) / 445(60.7%) | 510(69.6%) / 223(30.4%) | 642(87.6%) / 91(12.4%) |

---

## [3] split별 라벨 분포 — 1차 실험 대비 분포 이동 해소 확인

train 513일(2023-08-23~2025-09-30) / val 109일(2025-10-01~2026-03-18) / test 111일(2026-03-19~2026-08-28, 2026년 폭락 구간 포함)

### 방향 5-class

| split | N | -2 | -1 | 0 | +1 | +2 |
|---|---|---|---|---|---|---|
| train | 20 | 30 (5.8%) | 131 (25.5%) | 206 (40.2%) | 109 (21.2%) | 37 (7.2%) |
| train | 60 | 29 (5.7%) | 135 (26.3%) | 208 (40.5%) | 107 (20.9%) | 34 (6.6%) |
| train | 120 | 26 (5.1%) | 137 (26.7%) | 206 (40.2%) | 110 (21.4%) | 34 (6.6%) |
| val | 20 | 2 (1.8%) | 24 (22.0%) | 48 (44.0%) | 24 (22.0%) | 11 (10.1%) |
| val | 60 | 1 (0.9%) | 28 (25.7%) | 41 (37.6%) | 26 (23.9%) | 13 (11.9%) |
| val | 120 | 2 (1.8%) | 26 (23.9%) | 40 (36.7%) | 28 (25.7%) | 13 (11.9%) |
| test | 20 | 3 (2.7%) | 32 (28.8%) | 47 (42.3%) | 23 (20.7%) | 6 (5.4%) |
| test | 60 | 3 (2.7%) | 33 (29.7%) | 44 (39.6%) | 23 (20.7%) | 8 (7.2%) |
| test | 120 | 5 (4.5%) | 33 (29.7%) | 42 (37.8%) | 20 (18.0%) | 11 (9.9%) |

### 방향 3-class

| split | N | -1 | 0 | +1 |
|---|---|---|---|---|
| train | 20 | 161 (31.4%) | 206 (40.2%) | 146 (28.5%) |
| train | 60 | 164 (32.0%) | 208 (40.5%) | 141 (27.5%) |
| train | 120 | 163 (31.8%) | 206 (40.2%) | 144 (28.1%) |
| val | 20 | 26 (23.9%) | 48 (44.0%) | 35 (32.1%) |
| val | 60 | 29 (26.6%) | 41 (37.6%) | 39 (35.8%) |
| val | 120 | 28 (25.7%) | 40 (36.7%) | 41 (37.6%) |
| test | 20 | 35 (31.5%) | 47 (42.3%) | 29 (26.1%) |
| test | 60 | 36 (32.4%) | 44 (39.6%) | 31 (27.9%) |
| test | 120 | 38 (34.2%) | 42 (37.8%) | 31 (27.9%) |

### 변동성 2-class — 후보 3종 (고변동 비율)

| split | N | \|z\|>0.5 | \|z\|>1.0 | \|z\|>1.5 |
|---|---|---|---|---|
| train | 20 | 307(59.8%) | 153(29.8%) | 67(13.1%) |
| train | 60 | 305(59.5%) | 142(27.7%) | 63(12.3%) |
| train | 120 | 307(59.8%) | 148(28.8%) | 60(11.7%) |
| val | 20 | 61(56.0%) | 35(32.1%) | 13(11.9%) |
| val | 60 | 68(62.4%) | 38(34.9%) | 14(12.8%) |
| val | 120 | 69(63.3%) | 39(35.8%) | 15(13.8%) |
| test | 20 | 64(57.7%) | 28(25.2%) | 9(8.1%) |
| test | 60 | 67(60.4%) | 36(32.4%) | 11(9.9%) |
| test | 120 | 69(62.2%) | 36(32.4%) | 16(14.4%) |

### 1차 실험과의 대비 — 분포 이동 문제 해소 확인 (핵심)

| | 1차 실험(구 5-tier 절대임계값) | Task E 신규(방향 5-class, z ±0.5/±1.5) |
|---|---|---|
| train 지배 클래스 | 중립(0) **50.4%** | 중립(0) 39.3~41.1% (윈도우별) |
| test 지배 클래스 | 극단(-2) **31.8%** | 중립(0) 37.8~42.3% — **여전히 중립이 최빈, 극단으로 뒤집히지 않음** |
| test 극단(-2) 비율 | 31.8% | 2.7~4.5% |

1차 실험은 **train 중립 50.4% → test 극단 31.8%**로 지배 클래스 자체가 뒤집히는 붕괴였다. Task E
신규 라벨은 세 split 모두 중립(0)이 36.7~44.0% 범위에서 안정적으로 최빈 클래스를 유지하고,
극단(-2) 비율도 최대 5.8%(train, N=20)에 그쳐 어느 split에서도 지배적 클래스가 되지 않는다.
**분포 이동 문제는 해소된 것으로 판단한다.**

---

## [4] D-8 레짐 특성 3종 (split별)

| split | 거래일 | 전 거래일 평균\|cr\| | 평균\|초과수익률\| | KOSPI 평균\|cr\| |
|---|---|---|---|---|
| 전체 | 733일 (2023-08-23~2026-08-28) | 2.066% | 1.155% | 1.364% |
| train | 513일 (2023-08-23~2025-09-30) | 1.384% | 0.993% | 0.867% |
| val | 109일 (2025-10-01~2026-03-18) | 2.813% | 1.383% | 1.846% |
| test | 111일 (2026-03-19~2026-08-28) | 4.485% | 1.684% | 3.188% |

**해석**: KOSPI 자체의 평균 변동성은 train→test 구간에서 0.867% → 3.188%로 **약 3.7배** 뛴다
(2026년 폭락 반영). 반면 초과수익률(종목 변동에서 KOSPI 변동을 뺀 값)의 평균 변동은
0.993% → 1.684%로 **약 1.7배 증가에 그친다.** 시장 전체가 흔들린 폭의 상당 부분이 초과수익률
계산 과정에서 상쇄된다는 뜻이며, 롤링 z-score(D-2)와 KOSPI 차감이 레짐 변화를 실제로 상당히
흡수하고 있음을 정량적으로 보여준다 — D-3 개정("스트레스 구간을 제외하지 않아도 되는 이유")의
핵심 근거다.

---

## 확정 사항 (2026-08-30, 사람 결정)

| 항목 | 결정 | 근거 |
|---|---|---|
| 윈도우 N | **20/60/120 전부 사용** (하나로 좁히지 않음) | [1]에서 세 윈도우의 z 분포·[2]/[3]의 라벨 분포가 서로 거의 동일해 어느 하나가 다른 것보다 우월하다고 판단할 근거가 없었다. Task F에서 윈도우를 비교 축으로 그대로 유지해 모델 성능으로 최종 판단한다 |
| 방향 라벨 | **5-class와 3-class 둘 다 사용** | 둘 다 [3]에서 안정적인 분포를 보였고, 어느 세분화 수준이 신호를 더 잘 잡는지는 라벨 정의가 아니라 Task F 게이팅(TF-IDF+로지스틱회귀)에서 데이터로 판정하기로 이미 정해져 있었다(D-9) — 지금 하나로 좁힐 이유가 없다 |
| 변동성 라벨 | **\|z\| > 1.0** | 세 후보 중 중간값. `>0.5`는 고변동 비율이 58~61%로 사실상 다수클래스가 되어 "변동성이 큰 날"이라는 라벨의 변별력이 약하고, `>1.5`는 고변동 비율이 12% 안팎으로 줄어 표본이 5-class의 극단(-2) 클래스와 비슷한 수준까지 작아진다. `>1.0`은 정상/고변동이 대략 70/30으로 나뉘어 두 극단의 중간에서 가장 실용적인 균형을 보였다 |

---

## 주의사항

**5-class 극단 클래스(-2)는 val split에서 표본이 극히 적다** (윈도우별 0.9~1.8%, 1~2건 수준).
Task F에서 이 클래스의 precision/recall이 낮게 나오더라도 **모델의 한계가 아니라 표본 부족으로
먼저 해석할 것** — 특히 val 기준 게이팅·early stopping 지표를 볼 때 이 점을 감안해야 한다. train
(5.1~5.8%)·test(2.7~4.5%)는 상대적으로 여유가 있지만 그래도 5-class 중 가장 작은 클래스다.
