# 결과: 변동성 조기경보 검증

> ⚠️ **폐기됨(2026-09-06)** — 이 문서 전체가 GARCH `forecast(start=k)` 라벨링 버그로 인한
> 결과다(σ가 그날 자신의 수익률을 이미 재료로 쓰고 있었음). 버그 수정 후 재검증한 결과
> recall이 84.6%→0.7%로 무너져(p=0.4186, 유의 아님) 여기 기록된 조기경보 능력 자체가
> 착시였음이 확정됐다. **최신 결론은 `결과_TaskT_변동성예측_최종.md` 참고.** 이 문서는
> 실패 원인 추적 기록으로만 보존한다.

작성일: 2026-09-06
상위 문서: `결과_TaskT_방향예측_폐기.md`(방향 예측 폐기 배경) / `CLAUDE.md`
목적: 하이브리드(GARCH+Transformer) 변동성 예측 모델의 예측값을 "급변 사전 경보"로 쓸 수
있는지 3단계에 걸쳐 검증한 전체 과정과 최종 결론을 기록한다.

---

## [1] 배경

변동성 예측 모델(하이브리드 Transformer, GARCH(1,1) σ를 15번째 피처로 포함)이 GARCH·SMA20
baseline을 크게 이긴다는 것을 확인한 뒤, 자연스럽게 다음 질문이 제기됐다: **"갑작스런 등락/
폭락도 감지할 수 있는가?"**

우려는 구체적이었다 — GARCH 계열 모델은 "변동성 지속성"(어제 변동성이 크면 오늘도 크다)만
학습하는 구조라서, 예고 없는 급변(전쟁·정책 충격·수급 이벤트 등 완전히 새로운 정보)은
원리적으로 못 잡을 가능성이 높다. 이 프로젝트의 검증 대상 기간(2026년 상반기)이 마침
CLAUDE.md에 기록된 실제 폭락 사례(2026-02~07, 서킷브레이커 8회 발동, 코스피 월간 -22%)를
포함하고 있어, 이 질문을 실증적으로 검증할 좋은 사례가 됐다.

방법: 실제 |수익률|이 직전 60일 평균의 2배 이상인 날을 "급변일"로 정의하고, 하이브리드
모델이 그 전날 만든 예측 σ가 "경보"(직전 60일 예측σ평균의 1.5배 초과)를 발령했는지 확인 —
random walk/동전던지기와 같은 원칙으로 무작위 baseline과 비교.

---

## [2] 1차 검증 — 전체 급변일 기준 (2026-09-06)

test 구간(2025-09-16~2026-09-04, 8종목) 전체 급변일 298건에 대해 recall/precision을
계산했다.

| | Recall | Precision |
|---|---|---|
| 실제 모델 | **84.6%** | **72.6%** |
| 무작위 baseline(1000회 시뮬레이션) | 18.4%±2.1% | 15.7%±1.8% |
| p-value | **0.001** | — |

2026-02~07 폭락 구간이 8종목 전부에서 급변일로 포착됨(종목당 15~28건)을 확인했다.

**문제 제기**: 이 84.6%는 "국면 지속을 잘 추적한 것"인지 "국면 진입 자체(첫 신호)도 잡아낸
것"인지 구분이 안 된다 — 2026-02~07 급변 구간이 5~6개월간 지속된 국면이라, 같은 국면 안의
연속된 급변일들을 여러 번 맞히는 것만으로도 recall이 쉽게 높아질 수 있기 때문이다.

---

## [3] 2차 검증 — "국면 진입 첫날"만 (N=5)

급변일 중 직전 5거래일 이내에 다른 급변일이 없었던 날("고립된 첫날")만 골라 recall을
재계산했다.

| | 전체 급변일 recall | 첫날만 recall |
|---|---|---|
| 8종목 pooled | 84.6% | **91.3%** |

**예상과 정반대로 나왔다** — "국면 지속만 추적한다"는 가설이 맞다면 첫날 recall이 뚜렷이
낮아야 하는데, 오히려 소폭 더 높았다(8종목 중 6종목에서 첫날 recall이 전체와 같거나 높음).

---

## [4] 3차 검증 — N 민감도 + 피처 기여도 분석

### N 민감도 (N=5/10/20)

"첫날" 정의를 더 엄격하게(고립 기준 거래일을 5→10→20일로 확대) 좁혀가며 recall이 무작위
수준으로 떨어지는지 확인했다 — 만약 91.3%가 느슨한 정의(N=5)로 인한 착시라면, N을 늘릴수록
recall이 무너져야 한다.

| N | 첫날 수(test, 8종목) | Recall | 무작위 baseline | p-value |
|---|---|---|---|---|
| 5 | 115 | 91.3% | 18.4%±3.5% | 0.001 |
| 10 | 51 | 92.2% | 18.4%±5.5% | 0.001 |
| 20 | 17 | 88.2% | 18.4%±9.2% | 0.001 |

**recall이 무너지지 않았다.** N=20(표본 17건으로 작아졌지만)까지 88.2%를 유지했고 p-value는
세 지점 모두 0.001로 동일하게 강했다 — "느슨한 정의로 인한 착시" 가설은 기각됐다.

### 피처 기여도 (N=20 첫날 17건, 종목별 z-score 정규화 후 pooled 평균, D-5~D+1)

| k(D 기준) | garch_sigma | log_volume | bond_spread_10y_3y | recent_vol_ma20 |
|---|---|---|---|---|
| D-5 | -0.029 | -0.540 | +0.311 | +0.201 |
| D-4 | -0.016 | -0.487 | +0.302 | +0.177 |
| D-3 | -0.072 | -0.477 | +0.311 | +0.080 |
| D-2 | -0.062 | -0.199 | +0.338 | -0.017 |
| **D-1** | **-0.034** | -0.263 | +0.352 | -0.087 |
| **D0** | **+1.242** | +0.384 | +0.368 | -0.112 |
| D+1 | +1.471 | +1.041 | +0.363 | +0.259 |

**핵심 발견**: `garch_sigma`는 D-5~D-1 내내 완전히 평소 수준(z≈-0.03~-0.07)이다가 D0에서만
갑자기 +1.24로 튄다. 다른 세 피처(log_volume/bond_spread/recent_vol_ma20)도 D-5~D-2 구간에
사전 상승 패턴이 전혀 없다.

**메커니즘 해석**: "D0의 garch_sigma"는 실제로는 GARCH(1,1)의 재귀식(σ²(t)=ω+αε²(t-1)+
βσ²(t-1)) 구조상 **D-1일에 실현된 수익률을 재료로 계산된, D일을 예측하기 위한 값**이다(위
[1]의 GARCH 정의 및 `결과_TaskE_라벨링.md`류 문서들의 "sigma_t는 t 시점 미포함" 원칙과
동일 관용구, 상세 재귀식 검증은 이전 세션의 데이터 누수 감사에서 완료). 즉 이 점프가 의미하는
것은: **D-1일 자체가 "빅무브 기준선(2배)"은 못 넘었지만 상당히 큰 폭의 수익률이 실현된
날이었고, GARCH가 정확히 하루 지연으로 거기에 반응해 D일 예측치를 밀어올렸다**는 것이다.
D-5~D-2 구간에는 이런 전조가 전혀 없다.

---

## [5] 최종 결론

**"며칠 전부터의 조기경보 능력이 있다"는 가설은 성립하지 않는다.** D-5~D-2 구간에는 어떤
피처에도 사전 신호가 없다. 다만 **"D-1일의 전조적 움직임(기준선 미만이지만 상당히 큰 폭)을
놓치지 않고 하루 앞서 경보로 전환하는" 기능은 실증됐고, 이는 GARCH(1,1)의 설계 그 자체
(직전 1일 충격에 대한 정상적 반응)가 정확히 작동한 결과다.**

**판단 근거**: 완전히 예고 없는 돌발 사건(예: 전쟁 발발 당일)은 정의상 그 이전 데이터에
아무 흔적도 남기지 않으므로, 어떤 통계·ML 모델로도 원리적으로 감지가 불가능하다. 검증 대상
기간(2026년 상반기, 서킷브레이커 8회 발동 등 다사다난했던 시기)에도 이 이상의 조기 신호가
발견되지 않았다는 것은, 평상시에는 **"D-1 기반 익일 경보" 이상의 사전 신호가 이 데이터·이
피처 범위에는 존재하지 않을 가능성**을 시사한다.

**채택 결정**: 별도의 이상치 탐지 모델(Isolation Forest 등)을 새로 개발하지 않는다.
하이브리드 모델이 이미 매일 산출하는 예측 σ를 그대로 "D-1 기반 익일 경보"(예측σ > 직전
60일 예측σ평균의 1.5배) 용도로 겸용한다 — 별도 모델을 얹어도 이보다 더 이른 시점의 신호를
찾아낼 근거가 없다고 판단했다. 이 경보 규칙은 `가격예측_변동성_일일수집.py`의
`model_predictions.is_early_warning` 컬럼으로 매일 자동 산출·저장된다.

**표현상 주의**: 이 기능을 문서화·설명할 때 "며칠 전부터의 조기경보"라는 표현은 이번 검증
결과와 맞지 않는다 — 정확히는 **"D-1일 전조 신호 기반 익일(D일) 경보"**로 규정할 것.

---

## [6] 참고 — 사용된 일회성 분석 스크립트

- `volatility_early_warning_check.py` — 1차 검증(전체 급변일 기준)
- `volatility_early_warning_firstday_check.py` — 2차 검증(N=5 첫날)
- `volatility_early_warning_n_sensitivity_check.py` — 3차 검증(N=5/10/20 + 피처 기여도)

세 스크립트 모두 자동화/운영 코드가 아닌 일회성 진단이며, 파일 정리 시 `analysis/`로 이동할지
보존할지는 별도 논의 대상이다(CLAUDE.md 파일 정리 목록 참고).
