# 결과: Task F — 게이팅 및 검증

작성일: 2026-08-30
상위 문서: `TASK_EF_라벨링_비교실험.md`(Task F 지시서) / `결과_TaskE_라벨링.md`(Task E 라벨 결과) / `CLAUDE.md`
목적: Task F 게이팅(TF-IDF+로지스틱회귀) 실행, 그 과정에서 발견된 뉴스-라벨 매칭 누수와 수정,
이후 셔플·사전분포 검증, 익일(h=1)→주간(h=3/5/10) horizon 확장 재실험까지 전체 과정과 상세
수치를 보관한다. `CLAUDE.md`에는 결론과 방법론적 교훈만 요약하고 상세 표는 이 문서를 참조하도록
분리했다.

---

## 실행 조건

| 항목 | 값 |
|---|---|
| 대상 종목 | 005930(삼성전자) |
| 데이터 소스 | `daily_news`(`source='search_backfill'`) 제목만 (교차 평가 대비 학습-서빙 일치) |
| 기간 | `TRAIN_PERIOD_START`~`TRAIN_PERIOD_END` = 2023-08-23 ~ 2026-08-28 |
| split(h=1 기준) | train 513일(2023-08-23~2025-09-30, 뉴스 8,668건) / val 109일(2025-10-01~2026-03-18, 뉴스 2,231건) / test 111일(2026-03-19~2026-08-28, 뉴스 3,487건) — 누수 수정 전 뉴스 건수는 8,686/2,236/3,470건(귀속 거래일이 살짝 달라짐) |
| 라벨 | `daily_labels`(Task E z_score), (ticker, date)로 조인 — 방향 5-class(z ±0.5/±1.5), 방향 3-class(z ±0.5), 변동성 2-class(\|z\|>1.0) |
| 모델 | TF-IDF(char_wb 2-4gram, min_df=2) + `LogisticRegression(class_weight='balanced')` |
| 실행 스크립트 | `감성분석/taskf_gating.py`(h=1 게이팅), `감성분석/taskf_validate.py`(h=1 검증), `감성분석/taskf_gating_horizon.py`(h=3/5/10 게이팅+검증 통합), `감성분석/taskf_gating_basis.py`(basis 비교), `감성분석/taskf_gating_relevance_filter.py`(키워드 필터 비교), `감성분석/finbert_gating.py`(KR-FinBERT 실제 파인튜닝) |
| 실행 일자 | 2026-09-01(h=1 게이팅+누수 수정+검증), 2026-09-02(horizon 확장), 2026-09-06(label_basis 비교, 키워드 필터 비교, KR-FinBERT 파인튜닝) |

---

## [1] 시점 정렬 누수 발견 및 수정 (2026-09-01)

### 문제

최초 구현(`taskf_gating.py`)은 `pd.merge_asof(news, trading_calendar, direction="forward")`를
기본 옵션(`allow_exact_matches=True`)으로 호출했다. 이 때문에 **거래일에 발행된 뉴스가 그날
자신의 라벨에 매칭**되고 있었다. `search_backfill`/빅카인즈 둘 다 발행 "시각" 정보가 없어 D일
뉴스가 장중에 나왔는지 장 마감 후 그날 결과를 사후 서술한 것인지 구분할 수 없는데, 당일 라벨에
매칭하면 후자의 경우 "이미 벌어진 일을 사후 서술한 텍스트로 그날 라벨을 맞히는" 누수가 된다.

### 수정

`allow_exact_matches=False`로 변경 — **D보다 엄격히 뒤(> D)인 첫 거래일에만 매칭**한다. 이
규칙 하나가 거래일 뉴스와 휴장일 뉴스를 모두 처리한다(휴장일 뉴스는 원래도 자기 날짜가 거래일
후보가 아니므로 결과가 같다). `시장지표/feature_loader.py`의 `published_date < 거래일`
누수방지 관용구와 방향만 반대인 동일 패턴이다. **이것이 로드맵 Task D "안 B(완화)"의 실제
구현**이다 — `daily_news.target_date` 컬럼을 채우는 방식이 아니라 조회 시점에 즉석 조인하는
방식을 택했다.

### 수정 전/후 비교 (test macro F1, baseline 대비 Δ) — 9개 조합(h=1, 윈도우 3종)

| 라벨 | N | Δtest(수정 전, 당일 매칭·누수) | Δtest(수정 후, D+1 거래일) | 변화 |
|---|---|---|---|---|
| 방향 3-class | 20 | 0.1454 | 0.1090 | -25% |
| 방향 3-class | 60 | 0.1430 | 0.1226 | -14% |
| 방향 3-class | 120 | 0.1505 | 0.1188 | -21% |
| 변동성 2-class | 20 | 0.1030 | 0.0603 | -41% |
| 변동성 2-class | 60 | 0.1160 | 0.1009 | -13% |
| 변동성 2-class | 120 | 0.1124 | 0.1071 | -5% |
| 방향 5-class | 20 | 0.0860 | 0.0707 | -18% |
| 방향 5-class | 60 | 0.0829 | 0.0798 | -4% |
| 방향 5-class | 120 | 0.0879 | 0.0754 | -14% |

**9개 조합 전부 격차가 4~41% 줄었다** — 조합별 편차가 크다(가장 작게 깎인 방향 5-class N=60은
-4%, 가장 크게 깎인 변동성 2-class N=20은 -41%). **시점 정렬 없이는 성능이 최대 41%까지
과대평가될 수 있다는 것**이 실측 수치로 확인됐다.

### 상위 피처 변화 (방향 3-class, 수정 전 N=120 최고조합 → 수정 후 N=60 최고조합)

- **수정 전(당일 매칭)**: 상승(+1) `강세`, `신고가`, `상승`, `최고치` / 하락(-1) `신저가`,
  `최저`, `반토막`, `하락` — 결과를 그대로 서술하는 사후형(post-hoc) 어휘가 두드러짐
- **수정 후(D+1 매칭)**: 하락(-1) `신저가`, `부진`, `밑돌아`(실적 밑돌아 등) / 상승(+1)
  `주주총회`, `정기주주총회`, `경계현`(前 대표이사), `갤럭시s24`, `수혜`, `한국전자전` —
  주주총회·제품 출시·임원 관련 **이벤트성 어휘 비중이 늘어남**

날짜 파편·UI 텍스트(1차 실험의 실패 패턴)는 수정 전후 모두 나타나지 않았다. 수정 후 이벤트성
어휘 비중이 늘어난 것은 D+1 매칭이 의도대로 작동한다는 정황 근거이지만, 아래 [2]에서 보듯 이
"신호"조차 통계적으로는 신호가 아니었다.

---

## [2] 익일 예측(h=1) 게이팅 + 검증 (2026-09-01)

누수 수정 후 "9개 조합 전부 baseline 상회"가 진짜 신호인지 `감성분석/taskf_validate.py`로
검증했다. 대상은 각 라벨 유형에서 D+1 매칭 기준 최고 조합 3개: **방향 3-class/N=60, 변동성
2-class/N=120, 방향 5-class/N=60**.

### 레이블 셔플 테스트 (train 라벨만 30회 무작위 순열, 날짜-뉴스 대응은 유지)

| 조합 | 실제 Δtest | 셔플 Δtest 평균±표준편차 | 셔플 95% 구간 | 실제 위치 | p-value |
|---|---|---|---|---|---|
| 방향 3-class, N=60 | +0.1226 | +0.1402 ± 0.0140 | [+0.1132, +0.1629] | -1.26σ(평균보다 낮음) | 0.8710 |
| 변동성 2-class, N=120 | +0.1071 | +0.1109 ± 0.0136 | [+0.0897, +0.1338] | -0.28σ(평균보다 낮음) | 0.5806 |
| 방향 5-class, N=60 | +0.0798 | +0.0738 ± 0.0082 | [+0.0588, +0.0874] | +0.73σ | 0.2581 |

세 조합 모두 실제 Δ가 셔플 95% 구간 **안**에 있다. p-value 전부 0.05를 크게 상회 — **전부
유의하지 않음**. 방향 3-class와 변동성 2-class는 실제 Δ가 셔플 **평균보다도 낮다**.

### 클래스 사전분포 무작위 예측기 (200회) — 클래스 수가 다른 스킴 간 절대값 비교 기준

| 조합 | train 클래스 비율 | 무작위 기대 F1 | 다수결 baseline | 실제 모델 |
|---|---|---|---|---|
| 방향 3-class, N=60 | [0.314, 0.397, 0.288] | 0.3321 ± 0.0081 | 0.1946 | 0.3172 |
| 변동성 2-class, N=120 | [0.695, 0.305] | 0.4984 ± 0.0084 | 0.3874 | 0.4945 |
| 방향 5-class, N=60 | [0.064, 0.251, 0.397, 0.216, 0.073] | 0.1951 ± 0.0061 | 0.1167 | 0.1966 |

**세 조합 전부 실제 모델이 사전분포 무작위 예측기의 기대값보다 낮거나 거의 같다.** 다수결
baseline만 큰 폭으로 이길 뿐, 클래스 비율만 아는 무작위 예측기조차 못 이긴다 — 셔플 테스트와
독립적으로 같은 결론에 도달하는 두 번째 증거.

### "시드" 안정성 — 예상 밖 발견 + 부트스트랩 대체

`LogisticRegression(solver='lbfgs')`(기본값)는 **결정론적**이라 `random_state`만 바꿔서는
결과가 완전히 동일했다(표준편차 0.000000, 3개 조합 전부 확인). Transformer와 달리 이
파이프라인엔 학습 과정의 무작위성이 없어 문자 그대로의 시드 안정성 점검은 정보가 없다.

대신 **train 셋 부트스트랩 재추출(복원추출, 10회)**로 대체 점검했다:

| 조합 | 부트스트랩 Δtest 평균±표준편차 | 최소~최대 |
|---|---|---|
| 방향 3-class, N=60 | +0.1265 ± 0.0070 | +0.1136~+0.1357 |
| 변동성 2-class, N=120 | +0.0993 ± 0.0071 | +0.0864~+0.1087 |
| 방향 5-class, N=60 | +0.0772 ± 0.0069 | +0.0650~+0.0926 |

세 조합 모두 표준편차가 Δ의 절반 미만 — **상대적으로 안정적**이다. 하지만 안정적으로
재현되는 그 값 자체가 셔플 분포와 겹친다 — **"안정적으로 재현되는 착시"**라는 뜻이다.

### 표본 크기 (test split)

| 조합 | 클래스 | 거래일 수 | 뉴스 건수 |
|---|---|---|---|
| 방향 3-class, N=60 | -1 / 0 / +1 | 36 / 44 / 31 | 951 / 1437 / 1099 |
| 변동성 2-class, N=120 | 0(정상) / 1(고변동) | 75 / 36 | 2205 / 1282 |
| 방향 5-class, N=60 | -2 / -1 / 0 / +1 / +2 | **3** / 33 / 44 / 23 / 8 | 45 / 906 / 1437 / 672 / 427 |

3-class/2-class는 표본이 충분(최소 클래스도 30일 이상). 방향 5-class 극단(-2)은 test 3거래일뿐
— 판정 불가 수준.

### h=1 종합 판정

| 조합 | 판정 | 근거 |
|---|---|---|
| 방향 3-class, N=60 | **유의하지 않음** | p=0.871, 실제 Δ가 셔플 평균보다 낮음, 사전분포 무작위 예측기도 못 이김 |
| 변동성 2-class, N=120 | **유의하지 않음** | p=0.581, 실제 Δ가 셔플 평균보다 낮음, 사전분포 무작위 예측기와 사실상 동률 |
| 방향 5-class, N=60 | **판정 불가(표본 부족)** | test 최소 클래스 거래일 3개. p=0.258로 셔플과도 구분 안 되는 건 동일 |

---

## [3] 주간 단위 예측(h=3/5/10) 게이팅 + 검증 (2026-09-02)

"익일 예측은 노이즈 대비 신호가 너무 약할 수 있다"는 가설로 라벨을 h거래일 누적 초과수익률로
재설계해 재실험했다.

### 라벨 재설계

```
cum_excess_return_t,h = t부터 h거래일(t, t+1, ..., t+h-1) excess_return 합계
sigma_t,h = 직전 window_n개 앵커일의 cum_excess_return_*,h 표준편차 (t 시점 미포함)
z_t,h = cum_excess_return_t,h / sigma_t,h
```

h=1일 때 기존 정의와 수학적으로 완전히 같다(재적재 시 기존 4,902행 값 변경 0건으로 실측 확인).
`daily_labels`에 `horizon_h` 컬럼을 추가하고 PK를 `(ticker, date, window_n, horizon_h)`로
확장했다(테이블 분리가 아니라 컬럼 추가 — `window_n`을 다루던 기존 패턴과 일관성 유지, 기존
h=1 데이터는 보존). 데이터 끝부분(t+h-1이 가격 이력 범위를 넘는 날짜)은 excess_return/sigma/
z_score가 자동으로 NULL이 된다(전방 롤링 합 트릭, `min_periods=h` 미충족 시 NaN).

뉴스-라벨 매칭 규칙은 h=1과 완전히 동일하다(`allow_exact_matches=False`로 D보다 뒤인 첫
거래일 T에 매칭) — 달라지는 것은 T에 저장된 라벨의 의미뿐(하루치 → h거래일 누적).

### 게이팅 설계 축소

윈도우 N=60으로 고정(N=20/60/120 차이가 이미 ±1%p 이내로 미미함을 Task E에서 확인, D-2 참고),
라벨 3종 x horizon 3종 = **9개 조합**(27개에서 축소). 검증(블록 셔플 + 사전분포 무작위 예측기)을
게이팅과 함께 즉시 실행했다.

### 결과표 (test macro F1, baseline 대비 Δ 내림차순)

| 라벨 | h | test F1 | baseline | Δtest | 셔플 p | 사전분포 무작위 F1 | test 최소클래스 거래일 |
|---|---|---|---|---|---|---|---|
| 방향 3-class | 3 | 0.3251 | 0.1758 | +0.1493 | 0.5484 | 0.3264 | 32 |
| 변동성 2-class | 10 | 0.4727 | 0.3398 | +0.1328 | 0.9032 | 0.4967 | 39 |
| 방향 3-class | 5 | 0.3192 | 0.1982 | +0.1210 | 0.5161 | 0.3267 | 28 |
| 변동성 2-class | 5 | 0.4766 | 0.3679 | +0.1087 | 0.8387 | 0.4993 | 40 |
| 변동성 2-class | 3 | 0.5007 | 0.3990 | +0.1017 | 0.3871 | 0.5002 | 34 |
| 방향 5-class | 10 | 0.1828 | 0.0906 | +0.0922 | 0.4516 | 0.1807 | **1** |
| 방향 5-class | 5 | 0.1837 | 0.0997 | +0.0840 | 0.7097 | 0.1938 | **3** |
| 방향 5-class | 3 | 0.1753 | 0.0991 | +0.0762 | 0.8710 | 0.1905 | **3** |
| 방향 3-class | 10 | 0.3037 | 0.2416 | +0.0620 | 0.4839 | 0.3049 | 18 |

블록 셔플(h일 단위 블록으로 묶어 순서만 셔플 — 겹치는 누적 윈도우의 인접 표본 상관 보존) p-value
**전부 0.387 이상**. 방향 3-class(h=3,5,10)와 변동성 2-class(h=5,10)는 실제 F1이 사전분포
무작위 예측기 기대값보다 낮다. h=1과 동일하게 다수결 baseline만 크게(+0.06~0.15) 이긴다.

### Horizon(3/5/10) 경향 분석 — 이번 실험의 핵심 질문

| 라벨 | h=3 Δ(p) | h=5 Δ(p) | h=10 Δ(p) |
|---|---|---|---|
| 방향 5-class | +0.076(0.871) | +0.084(0.710) | +0.092(0.452) |
| 방향 3-class | +0.149(0.548) | +0.121(0.516) | +0.062(0.484) |
| 변동성 2-class | +0.102(0.387) | +0.109(0.839) | +0.133(0.903) |

**뚜렷한 개선 경향이 없다.** 방향 5-class는 raw Δ가 h와 함께 소폭 늘지만(0.076→0.092) 표본이
함께 무너진다(test 최소클래스 거래일 3→3→1, 판정 불가 수준). 방향 3-class는 h가 길어질수록
Δ가 오히려 **줄어든다**(0.149→0.062). 변동성 2-class는 raw Δ는 늘지만(0.102→0.133) p-value가
함께 나빠진다(0.387→0.903) — 누적 윈도우가 길수록 인접 표본 상관이 강해져 셔플 null 자체도
함께 벌어지기 때문이다. **horizon을 늘려도 신호 대 노이즈 비가 개선된다는 근거는 없다.**

### 상위 피처

유의한 조합이 없어 생략(스크립트가 자동으로 건너뛰도록 설계 — 신호가 확인되지 않은 조합의
피처를 사후에 들여다보는 것은 해석 남용 위험이 있다고 판단).

---

## [4] 종합 결론

1. **현재 데이터(005930 단일 종목, 약 3년, test 111거래일) 범위에서는 뉴스 텍스트와
   초과수익률 사이에 이 파이프라인으로 검출 가능한 관계가 없다.** h=1(익일)과 h=3/5/10(주간
   누적) 모두 동일한 결론에 도달했다 — "익일이라 안 됐다"는 가설은 명확히 기각됐다.
2. Task T-1이 "가격+거시지표만으로는 익일 방향성이 무작위 수준과 구분 안 됨"으로 확정했던 것과
   같은 성격의 결론이 뉴스/감성 트랙에서도 확인됐다.
3. **중요한 방법론적 발견**: macro F1에서 다수결 baseline을 이기는 것은 신호의 증거가 **아니다**.
   `class_weight='balanced'` + 고차원 희소 TF-IDF 파이프라인은 라벨이 무작위여도 macro F1이
   다수결 baseline을 기계적으로 상회하는 경향이 있다(균형 잡힌 예측을 보상하는 지표 특성 +
   고차원 노이즈 적합). **앞으로 이 파이프라인 계열로 신호 유무를 판정할 때는 반드시 (a) 레이블
   셔플/블록 셔플 테스트, (b) 클래스 사전분포 무작위 예측기 비교를 함께 수행할 것** — 다수결
   baseline 비교만으로는 착시에 빠질 수 있다.
4. **KR-FinBERT 투입은 근거 없음 — 보류한다.** 더 무거운 모델을 투입해도, 게이팅 단계에서
   확인되지 않은 신호를 찾아낼 가능성은 낮다고 판단한다(Task A의 KoBERT 1차 실험도 TF-IDF
   baseline과 동률이었던 선례와 같은 맥락).

---

## [5] 절대수익률 vs 초과수익률 비교 실험 (2026-09-06)

### 배경

기존 라벨은 `excess_return = 종목 change_rate − KOSPI change_rate`로 시장 전체 움직임을
제거한다. 그런데 이 방식이 "시장 전체에 좋은 뉴스"로 인한 신호까지 상쇄시킬 수 있다는 우려가
제기됐다 — 예를 들어 반도체 업황 전반에 대한 긍정적 뉴스는 삼성전자만의 초과 성과가 아니라
KOSPI 자체에도 반영될 텐데, 초과수익률 방식은 이런 신호를 지워버린다는 것.

이를 확인하기 위해 KOSPI를 빼지 않은 순수 `change_rate`(종목 자체 등락률) 기준 z-score를
`label_basis='absolute_return'`로 `daily_labels`에 추가 적재하고(`sigma_t = 직전 N거래일
change_rate 표준편차`, `z_t = change_rate_t / sigma_t` — 방향/변동성 라벨 파생 함수는
`excess_return` 라벨과 완전히 동일하게 재사용), 기존 `excess_return` 라벨과 나란히
게이팅+검증했다.

### 스키마 변경

`daily_labels`에 `label_basis VARCHAR(20)` 컬럼 추가, PK를 `(ticker, date, window_n,
horizon_h, label_basis)`로 확장(운영 DB ALTER TABLE 적용, 기존 행은 전부
`label_basis='excess_return'`으로 보존 — 값 변경 없음). `excess_return` 컬럼명은 그대로
재사용하며 `label_basis`에 따라 의미가 갈린다(`'excess_return'`=종목-KOSPI 누적값(기존),
`'absolute_return'`=종목 순수 change_rate 누적값) — `horizon_h` 도입 때 같은 컬럼이 h=1/h>1
두 의미를 겸했던 것과 동일한 방식. 상세는 `CLAUDE.md` DB 스키마 절 "daily_labels" 참고.

### 실행 조건

윈도우 N=60 고정(D-2/Task E에서 N=20/60/120 차이가 ±1%p 이내로 미미함을 이미 확인 —
`taskf_gating_horizon.py`와 동일한 축소 근거), horizon h=1(익일)과 h=3([3]의 h=3/5/10
실험에서 raw Δtest가 가장 컸던 조합인 방향 3-class/h=3, +0.1493을 대표로 채택) 비교. 뉴스
매칭 규칙(D일 뉴스 → D보다 뒤인 첫 거래일, `allow_exact_matches=False`)은 그대로 유지.
검증은 블록 셔플(h=1은 block_size=1, h=3은 block_size=3 — 겹치는 누적 윈도우로 인한 인접
표본 상관을 보존한 채 텍스트-라벨 대응만 끊음, 30회) + 클래스 사전분포 무작위 예측기(200회).
실행 스크립트: `감성분석/taskf_gating_basis.py`.

### 종합 비교표 (test macro F1, baseline 대비 Δ 내림차순)

| basis | 라벨 | h | test F1 | baseline | Δtest | 셔플p | 사전분포F1 | 판정 |
|---|---|---|---|---|---|---|---|---|
| excess_return | 방향 3-class | 3 | 0.3248 | 0.1747 | +0.1501 | 0.548 | 0.3269 | 유의하지 않음 |
| absolute_return | 방향 3-class | 3 | 0.3332 | 0.1865 | +0.1467 | 0.452 | 0.3294 | 유의하지 않음 |
| excess_return | 방향 3-class | 1 | 0.3172 | 0.1946 | +0.1226 | 0.871 | 0.3321 | 유의하지 않음 |
| absolute_return | 방향 3-class | 1 | 0.3136 | 0.1963 | +0.1173 | 0.710 | 0.3268 | 유의하지 않음 |
| absolute_return | 변동성 2-class | 1 | 0.4958 | 0.3938 | +0.1020 | 0.645 | 0.5001 | 유의하지 않음 |
| excess_return | 변동성 2-class | 1 | 0.4883 | 0.3874 | +0.1009 | 0.613 | 0.4976 | 유의하지 않음 |
| excess_return | 변동성 2-class | 3 | 0.5005 | 0.4000 | +0.1005 | 0.419 | 0.5003 | 유의하지 않음 |
| absolute_return | 방향 5-class | 3 | 0.2112 | 0.1119 | +0.0994 | 0.161 | 0.1958 | 판정 불가(표본 부족) |
| absolute_return | 변동성 2-class | 3 | 0.5101 | 0.4188 | +0.0912 | 0.516 | 0.4997 | 유의하지 않음 |
| absolute_return | 방향 5-class | 1 | 0.2033 | 0.1178 | +0.0855 | 0.258 | 0.1947 | 판정 불가(표본 부족) |
| excess_return | 방향 5-class | 1 | 0.1966 | 0.1167 | +0.0798 | 0.290 | 0.1951 | 판정 불가(표본 부족) |
| excess_return | 방향 5-class | 3 | 0.1749 | 0.0984 | +0.0765 | 0.903 | 0.1909 | 판정 불가(표본 부족) |

12개 조합(basis 2종 x 라벨 3종 x h 2종) 전부 **"유의하지 않음"** 또는 **"판정 불가(표본
부족)"**. 셔플 p-value 전부 0.16 이상(대부분 0.4~0.9)이고, 여러 조합에서 실제 모델 macro F1이
사전분포 무작위 예측기 기대값과 거의 같거나 낮다 — [2]/[3]과 동일한 "다수결 baseline만 크게
이기는 착시" 패턴이 basis를 바꿔도 반복된다.

### 직접 대응 비교 (같은 라벨 x h, excess_return vs absolute_return)

| 조합 | excess_return Δ(p) | absolute_return Δ(p) |
|---|---|---|
| 방향 5-class, h=1 | +0.0798 (0.290) | +0.0855 (0.258) |
| 방향 5-class, h=3 | +0.0765 (0.903) | +0.0994 (0.161) |
| 방향 3-class, h=1 | +0.1226 (0.871) | +0.1173 (0.710) |
| 방향 3-class, h=3 | +0.1501 (0.548) | +0.1467 (0.452) |
| 변동성 2-class, h=1 | +0.1009 (0.613) | +0.1020 (0.645) |
| 변동성 2-class, h=3 | +0.1005 (0.419) | +0.0912 (0.516) |

raw Δ 차이는 미미하고(대부분 ±0.005~0.02p 이내) 방향도 일관되지 않는다 — 방향 5-class는
absolute_return이 두 horizon 모두 소폭 우세, 변동성 2-class/h=3은 excess_return이 소폭
우세, 나머지는 excess_return이 근소 우세. 어느 쪽도 통계적으로 유의하지 않으므로 이 차이
자체가 의미 있는 패턴이라고 볼 근거는 없다.

### 상위 피처 구성비 분석 (요구사항 4)

유의한 조합이 하나도 없어 **생략했다**(`taskf_gating_horizon.py`/`taskf_gating_basis.py`
공통 설계 원칙 — 신호가 확인되지 않은 조합의 상위 피처를 사후에 들여다보는 것은 해석 남용
위험이 있다고 판단, 스크립트가 유의한 조합이 있을 때만 자동으로 수행하도록 짜여 있음). 따라서
"absolute_return 상위 피처에 업황/거시 어휘가 실제로 늘었는지"는 이번 실험 범위에서 확인할
근거 데이터 자체가 나오지 않았다.

### 결론 — "KOSPI 차감으로 시장 전체 신호가 상쇄된다" 가설 기각

KOSPI를 차감하지 않은 절대수익률 라벨로 바꿔도 유의한 신호는 나오지 않았다. 초과수익률 방식이
"시장 전체에 좋은 뉴스" 신호를 지워버려서 Task F가 신호를 못 찾은 것이라는 가설은, **이
데이터(005930 단일 종목, 약 3년, test 111거래일)와 이 파이프라인(TF-IDF+로지스틱회귀) 범위
에서는 기각된다.** [4]의 종합 결론("뉴스 텍스트와 초과수익률 사이에 검출 가능한 관계 없음")은
라벨의 시장 조정 방식과 무관하게 유지된다 — 문제는 초과수익률이라는 라벨 정의 자체가 아니라
더 근본적인 층(표본 크기, 종목 단일성, 뉴스-가격 관계 자체의 부재 가능성 등, [8] 미결 사항
참고)에 있을 가능성이 높다.

---

## [6] 키워드 관련성 필터 사후 검증 (2026-09-06)

### 배경 및 목적

기존 필터(제목에 종목명 포함 + 언론사 화이트리스트)는 실적/공시 같은 사건성 기사와 제품
홍보·사회공헌 등 무관한 기사가 섞여 있다. 재크롤링 없이 이미 있는 `daily_news`
(`search_backfill`) 기사에 **주가 민감 키워드**가 제목에 하나라도 포함된 기사만 "관련성
높음"으로 사후 필터링해, 노이즈를 줄이면 신호가 드러나는지 확인했다. 원본 데이터는 건드리지
않고 런타임 정규식 필터로만 적용(`감성분석/taskf_gating_relevance_filter.py`).

키워드(사람 지정, "미래 주가에 영향을 줄 사건"만 포함 — 이미 일어난 가격 변동을 서술하는
"상한가/급등/급락" 등과 "실적/공시/배당/자사주"처럼 사건/결과 서술이 애매한 단어는 의도적으로
제외): `계약, 수주, 소송, 특허, 인수, 합병, 감산, 증산, 리콜, 파업, 제재, 승인, 허가,
유상증자, 무상증자, 감사, 목표주가, 투자의견`

### 사전 점검 — 필터 후 남는 기사 수

전체 14,386건 → 관련성 높음 **1,050건(7.3%)**, 10% 기준 미달. split별 5.2%(train)/
4.6%(val)/**14.3%(test)**로 test에 불균형하게 몰려 있음 — 원인은 아래 편중 확인 참고.
절대 건수(1,050건)는 TF-IDF 학습에 무리 없는 수준이라 그대로 진행했다.

### 게이팅 비교 (필터 전 vs 후, 4개 대표 조합 x N=200 셔플)

윈도우 N=60 고정, horizon h=1/3, basis excess_return/absolute_return 대표 조합 4개.

| 구분 | basis | 라벨 | h | test F1 | baseline | Δtest | 셔플p(N=200) | 사전분포F1 | 판정 |
|---|---|---|---|---|---|---|---|---|---|
| all | excess_return | 방향 3-class | 3 | 0.3248 | 0.1747 | +0.1501 | 0.557 | 0.3269 | 유의하지 않음 |
| relevant | excess_return | 방향 3-class | 3 | 0.3527 | 0.2240 | +0.1287 | 0.080 | 0.2970 | 유의하지 않음 |
| all | absolute_return | 방향 3-class | 3 | 0.3332 | 0.1865 | +0.1467 | 0.428 | 0.3294 | 유의하지 않음 |
| relevant | absolute_return | 방향 3-class | 3 | 0.3628 | 0.2113 | +0.1515 | 0.085 | 0.3101 | 유의하지 않음 |
| all | excess_return | 변동성 2-class | 1 | 0.4883 | 0.3874 | +0.1009 | 0.622 | 0.4976 | 유의하지 않음 |
| relevant | excess_return | 변동성 2-class | 1 | 0.4987 | 0.3498 | +0.1489 | 0.149 | 0.4808 | 유의하지 않음 |
| all | absolute_return | 변동성 2-class | 1 | 0.4958 | 0.3938 | +0.1020 | 0.577 | 0.5001 | 유의하지 않음 |
| relevant | absolute_return | 변동성 2-class | 1 | 0.4507 | 0.4200 | +0.0308 | 0.876 | 0.4987 | 유의하지 않음 |

8개 조합 전부 최종 "유의하지 않음". 방향 3-class/h=3 필터 후 두 basis(p=0.080, 0.085)가 가장
근접했다.

### 방법론적 발견 — 셔플 해상도 경계 오판

초기 관례대로 `N_SHUFFLE=30`으로 돌렸을 때 `[relevant/excess_return/방향3-class/h=3]`이
**p=0.0323(=1/31, N=30에서 나올 수 있는 최소 0 초과 p값 그 자체)**으로 "유의함" 판정을
받았다. `N=200`으로 재검증하니 **p=0.0796으로 뒤집혔다**(실제 Δ가 셔플 95% 상단을 못 넘음).
이 경계 오판 재발을 막기 위해 스크립트 기본값을 처음부터 N=200으로 수정했다.

### 편중 확인 — "파업" 사태 단일 사건 의존

위 근접 조합을 ablation한 결과, `relevant` test 500건 중 **405건(81%)이 "파업" 키워드에
매칭**됐고 그중 다수가 **2026년 5월 둘째~셋째 주(삼성전자 창사 이래 첫 총파업 협상·타결
사태)** 단 2주에 집중돼 있었다. `파업` 매칭 기사를 제외하고 재실행하면 표본이 500→95건으로
급감했고, 유의성은 회복되지 않았다(p=0.129) — 근접했던 결과가 독립적인 여러 사건의 신호가
아니라 단일 사건 하나에 의존한 취약한 결과였음을 뒷받침한다.

### 결론

키워드 필터로 노이즈를 줄여도 유의한 신호는 나오지 않았다. 이 필터는 최종 채택하지 않으며,
아래 [7] KR-FinBERT 실험은 이 필터(파업 사태 편향 확인됨)를 적용하지 않고 **전체 기사**로
진행한다.

---

## [7] KR-FinBERT 실제 파인튜닝 검증 (2026-09-06)

### 대상 조합 및 표본

지금까지 게이팅에서 가장 나았던 조합(raw Δtest 최댓값) 하나를 골라 실제로 KR-FinBERT를
파인튜닝했다: **`label_basis=excess_return` / 방향 3-class(z ±0.5) / `window_n=60` /
`horizon_h=3`**, 관련성 필터 **미적용**(위 [6]에서 파업 사태 편중이 확인돼 이번 대상에서는
제외 — 전체 기사 사용), 제목만, 매칭 규칙은 기존과 동일(D일 뉴스 → D보다 뒤인 첫 거래일,
`allow_exact_matches=False`). 표본은 TF-IDF 게이팅과 완전히 동일: train 8,668건 / val
2,231건 / test 3,487건(거래일 기준 513/109/111일).

### 파인튜닝 설정

- 모델: `snunlp/KR-FinBert`, `num_labels=3` (`AutoModelForSequenceClassification`)
- 부분 freeze: `감성분석/kobert_train.py`와 동일한 정책 — 임베딩 + 인코더 0~8 고정,
  9/10/11 + pooler + classifier만 학습. 총 101,403,651개 중 **21,856,515개(21.6%)** 학습
  (KoBERT 1차 실험의 23.7%와 비슷한 규모)
- `AdamW(lr=1e-5)` + `get_linear_schedule_with_warmup`(warmup 10%), class weight
  `CrossEntropyLoss`, early stopping(val macro F1 기준, patience=2, 최대 10 epoch)
- 입력: title 단일 시퀀스(기존 `kobert_dataset.NewsDataset`은 title+summary sentence-pair라
  이번 요구사항 "제목만"에 맞춰 `finbert_gating.py`에 별도 `TitleOnlyDataset` 정의),
  max_length=64(제목 평균 33자·최대 55자라 128 불필요)
- 결과: **epoch 3에서 val macro F1 최고(0.3122)**, patience=2로 epoch 5에 early stopping.
  **학습 소요 87.4초**(부분 freeze 덕에 매우 빠름)

### 환경 이슈 — snunlp/KR-FinBert 로드 우회 (투명성 기록)

`snunlp/KR-FinBert`는 safetensors 없이 `pytorch_model.bin`만 제공한다. 설치된
transformers는 **CVE-2025-32434**(`torch.load` 취약점) 때문에 torch<2.6에서 이런
체크포인트의 로드 자체를 거부한다. 이 프로젝트의 torch는 2.5.1+cu121(CLAUDE.md 환경 절
명시)이며 이번 실험 하나 때문에 임의로 업그레이드하지 않기로 했다. 대신
**`감성분석/finbert_gating.py` 스크립트 안에서만**
`transformers.modeling_utils.check_torch_load_is_safe`를 no-op으로 몽키패치해 우회했다 —
서울대 NLP 연구실이 공개한 잘 알려진 체크포인트로 신뢰할 수 있는 소스라고 판단했다. **이
패치는 해당 스크립트를 실행하는 프로세스 안에서만 유효하며, 다른 파일이나 프로젝트의
나머지 부분에는 전혀 영향을 주지 않는다.**

### 검증 절충안 — 고정 인코더 + 헤드 재학습 (N=50)

BERT 파인튜닝을 셔플마다 전체 재학습하는 것은 비현실적이라 다음 절충안을 채택했다: 실제
라벨로 1회 파인튜닝한 인코더를 고정 피처 추출기로 재사용하고, 셔플마다 로지스틱회귀
분류 헤드만 다시 학습(N=50회, `블록 셔플` block_size=3). 사전분포 무작위 예측기 비교는
계산량이 적어 절충 없이 원안대로 200회 실행했다.

**한계 2가지(보고서에 명시)**:
1. 인코더 자체를 재학습하지 않으므로 "전체 구조가 노이즈에 얼마나 과적합될 수 있는가"는
   측정하지 못하고, "고정 표현 위에서 헤드가 노이즈를 얼마나 분리해낼 수 있는가"만 측정한다.
2. 그 인코더가 실제 라벨로 이미 파인튜닝된 것이므로 셔플 귀무분포가 완전히 깨끗한 null이
   아니다 — 실제 신호가 인코더 표현에 이미 녹아있을 수 있다는 뜻이며, 이는 오히려 검증을
   보수적으로 만들기보다 해석을 흐릴 수 있는 방향의 한계다.

(오늘 [6]에서 겪은 "N=30 → p=1/31 경계 오판"을 반복하지 않기 위해 처음부터 N=50으로 실행.)

### 결과 비교 — KR-FinBERT vs TF-IDF (동일 조합)

| 지표 | KR-FinBERT | TF-IDF+로지스틱회귀 |
|---|---|---|
| test macro F1 | 0.3257 | 0.3248 |
| baseline(최빈클래스) | 0.1747 | 0.1747 |
| Δtest | +0.1510 | +0.1501 |
| accuracy | 0.3307 | — |
| 사전분포 무작위 예측기 기대 F1 | **0.3269 ± 0.0078** | 0.3269 ± 0.0078 |
| 실제 모델이 사전분포 무작위보다 높은가 | **아니오**(0.3257 < 0.3269) | 아니오 |
| 셔플 검증 | 헤드재학습 N=50, 실제Δ+0.1427 vs 셔플평균+0.1572, p=**0.8235** | N=200, p=0.557 |
| 최종 판정 | **유의하지 않음** | 유의하지 않음 |

### 핵심 발견

1. **KR-FinBERT의 test macro F1(0.3257)이 클래스 사전분포만 아는 무작위 예측기의 기대값
   (0.3269)보다도 낮다.** 파인튜닝된 BERT가 텍스트를 전혀 보지 않고 학습 데이터의 클래스
   비율대로 찍는 무작위 예측기보다 못한 성능을 낸 것 — TF-IDF와 성능이 거의 동일한 것도
   우연이 아니라 둘 다 "클래스 균형에 맞춰 찍는 수준"으로 수렴한 결과로 해석된다.
2. **고정 임베딩 + 로지스틱회귀 헤드만 새로 학습한 결과(F1=0.3174)와 전체 파인튜닝 결과
   (F1=0.3257)의 차이가 미미하다.** 파인튜닝이 단순 선형 헤드보다 실질적으로 유의미한 추가
   학습을 하지 못했다는 뜻이다.

### Sanity check — attention 상위 토큰

`sdpa` 어텐션 구현은 `output_attentions`를 지원하지 않아 `eager`로 재구성해(학습된
체크포인트 그대로) 확인했다. test 6개 샘플 결과:

- attention이 `[CLS]`/`[SEP]` 구조 토큰과 조각난 서브워드(`##사`, `##더`, `##버리`, `##닥`
  등)에 집중되고 의미 있는 핵심 단어에는 크게 쏠리지 않았다 — 1차 KoBERT 실패(날짜 파편/UI
  텍스트에 꽂힘)와 형태는 다르지만 "내용을 제대로 읽고 있지 않다"는 성격은 유사하다.
- 예측이 내용과 직관적으로 맞지 않는 사례가 다수: "15조원 자사주 소각 결정"(통상 호재)→중립
  예측, "당장 출근하고 싶은 기업 1위"(SK하이닉스 관련 긍정 기사)→하락 예측, "빅스비에
  퍼플렉시티 결합"(AI 기능 소개)→하락 예측. 오늘([6]) 발견한 "사후 서술" 패턴과는 다르지만,
  내용 기반의 일관된 판단으로 보기 어렵다는 점은 동일하다.

### 결론

KR-FinBERT를 실제로 투입해도 TF-IDF 대비 개선이 없고, 오히려 사전분포 무작위 예측기에도
못 미치는 수준이다. [4]에서 게이팅 단계만으로 내렸던 **"KR-FinBERT 투입은 근거 없음 —
보류한다"는 판단이 실제 파인튜닝으로 재확인·확정됐다.** 더 무거운 모델이 게이팅에서 못 찾은
신호를 찾아내는 상황은 이번에도 재현되지 않았다.

### 향후 개선 가능성 (미검증 가설 — 이번 프로젝트 범위에서는 시도하지 않음)

아래 두 방향은 조건이 달라지면 재검토할 만하지만, 이번 실험으로 검증한 것은 아니다.

**(a) 장 시작 전 뉴스만 분리했을 때의 가능성**: 현재 데이터는 발행 시각 정보가 없어(날짜만)
장중/장후/장전 뉴스를 구분하지 못한다. "장 마감 후~다음 장 시작 전(예: 오전 9시)" 뉴스만
분리할 수 있다면 사후 서술성 기사(그날 있었던 가격 변동을 다루는 기사)가 자연히 줄어 신호
대 노이즈 비가 개선될 가능성이 있다. 다만 검증하려면 (i) 언론사 원문 페이지의
`article:published_time` 메타태그 등으로 시각 정보를 확보하고 (ii) 기존 원문 재크롤링 또는
신규 수집분 누적(최소 수개월~1년)이 필요해 이번 프로젝트 일정상 시도하지 못했다.

**(b) 종목별 맞춤 관련성 필터의 가능성**: 이번 [6]의 키워드 필터는 모든 종목에 공통 적용
가능한 일반 키워드였다. 종목마다 특화된 맥락(반도체 업종 특유의 키워드, 특정 사업부 이슈
등)을 사람이 직접 분석해 종목별로 다른 필터를 설계하면 관련성이 더 높아지고 신호가 개선될
가능성이 있다. **다만 의도적으로 채택하지 않았다** — 이 프로젝트는 여러 종목으로 확장
가능한 자동화 파이프라인을 목표로 하는데(Task C 섹터 분산 확장 원칙), 종목마다 사람이
수작업으로 키워드를 튜닝해야 한다면 확장할 때마다 반복적인 수작업이 필요해져 자동화 설계
원칙과 충돌한다.

---

## [8] 미결 사항 — 다음 방향 후보 (결정 아님, 선택지 나열)

- **종목 확장(Task C)**: 현재 005930 단일 종목·약 3년 표본이 근본적으로 작다. 섹터 분산
  종목(현대차·LG화학·KB금융·삼성바이오로직스·NAVER, `constants.STOCKS`에 이미 비활성으로
  등록됨)을 추가하면 표본이 늘고, 여러 종목에 걸쳐 재현되는지도 확인할 수 있다.
- **기간 확장**: `NEWS_BACKFILL_START`를 더 앞당기거나(과거 조회 가능 기간 재확인 필요), 앞으로
  데이터가 쌓이길 기다려 재검증하는 방법.
- **데이터 소스 교차 검증**: `daily_news_bigkinds`(20,053건, 3년 커버)로 같은 검증을 반복해
  크롤링 소스 특유의 문제(품질 필터, 커버리지 공백 등)인지 확인.
- **문제 재정의**: 방향/변동성 라벨이 아니라 다른 타겟(예: 거래량 급증, 특정 이벤트 발생 여부)을
  시도하거나, 뉴스를 개별 기사가 아니라 일별 집계 피처(기사 수, 언론사 다양성 등)로 바꿔보는 방법.
  ✅ 2026-09-06: "개별 기사 유지가 KR-FinBERT 전환을 염두에 둔 요구사항이라 재검토 필요"라는
  단서는 해소됐다 — [7]에서 개별 기사 유지 + 실제 KR-FinBERT로 검증까지 마쳤고 신호가
  없음을 확정했으므로, 남는 것은 순수하게 "일별 집계 피처로 바꾸면 다를까"라는 별개 질문이다.
- **원인 진단 자체를 목표로 전환**: 신호가 없다는 결론 자체를 "왜 없는가"(정보 효율적 시장,
  단일 종목 표본 부족, 라벨 정의 문제 등) 분석하는 케이스 스터디로 전환.

이 목록은 후보 나열이며 결정하지 않았다 — 다음 단계는 사람이 정한다.
