# 결과: Task T 변동성 예측 — 진행 경과 종합 (2026-09-06)

상위 문서: `결과_TaskT_방향예측_폐기.md`(방향 예측 폐기 배경, 상세) / `결과_변동성_조기경보_검증.md`
(⚠️ **버그 있던 버전 — 아래 [3] 참고, 폐기 대상**) / `CLAUDE.md`

목적: 2026-09-06 하루 동안 진행된 변동성 예측 트랙 전체(전환 배경 → GARCH baseline →
치명적 라벨링 버그 발견·수정 → 재검증 → Parkinson 발견 → 하이브리드/원본시퀀스 실험 →
과적합·분산붕괴 진단 → 50종목 확장·최종 검증)를 시간순으로 정리한다. **8종목 구간까지는
학습 기반 모델이 baseline을 넘지 못했으나, [10]~[11]의 50종목 확장으로 오늘 처음 통계적으로
유의한 개선이 확인됐다** — 다만 자동화 반영·배포 게이트 확정 등은 다음 세션 과제로 남아
최종 결론은 아니다.

> ⚠️ **종목명 정정**: 이 문서와 `constants.py`에서 종목코드 `034730`은 처음부터 끝까지
> 일관되게 SK 주식회사(지주회사) 데이터였다. 확장 초기에 이 코드를 "현대건설"로 잘못
> 이름표를 붙였던 것을 50종목 확장 작업 중 발견해 정정했다(현대건설의 실제 코드는 000720,
> 별도 미등록). **가격 데이터·계산 결과 자체는 처음부터 정확했고 이름표만 틀렸던 것**이라
> 이 문서의 모든 034730 관련 수치는 그대로 유효하다.

---

## [1] 방향 예측 폐기 배경 (요약, 상세는 `결과_TaskT_방향예측_폐기.md`)

Task T-1(단일 종목) + 이번 세션(8종목 pooled + 종목 임베딩) 총 4번의 독립 평가에서 가격
방향(상승/하락) 예측이 전부 무작위 수준으로 확정됐다 — Random Walk/동전던지기/사전분포
무작위 예측기/레이블 셔플(N=7) 전부 통과 못함. 뉴스/감성 트랙(Task A~F)의 "신호 없음"
결론과 같은 성격이라 방향 예측 자체를 폐기하고 변동성(|수익률|) 예측으로 전환했다.

---

## [2] 변동성 예측 전환과 GARCH baseline 최초 발견 (⚠️ 버그 있던 수치, 아래 [3]에서 정정됨)

GARCH(1,1)(`arch` 패키지, 로그수익률×100, 종목별 독립 적합, train만으로 파라미터 추정 후
고정해 전체 구간 재귀 적용)을 SMA20(직전 20일 평균 |수익률|)과 비교하는 학계 표준 baseline
구축 첫 실행에서:

| | RMSE | MAE |
|---|---|---|
| GARCH(1,1) | (버그 버전) SMA 대비 약 14% 개선 | — |
| 하이브리드(GARCH σ를 15번째 피처로 추가한 Transformer) | GARCH 대비 42~43% 개선(8/8 종목) | — |

조기경보(급변 사전 감지) 검증도 이 버전으로 진행해 "84.6% recall, p=0.001, 국면 진입 첫날은
오히려 91.3%"라는 결과를 얻었다. **이 절의 수치는 전부 [3]의 버그로 인한 착시였음이 이후
밝혀졌다 — 역사적 기록으로만 남긴다.**

---

## [3] 라벨링 버그 발견과 수정

### 버그 내용

`가격예측/garch_baseline.py`의 `forecast_with_fixed_params()`(구 `fit_and_forecast_garch()`
내부 로직)가 `arch` 패키지의 `forecast(start=k, horizon=1)` 결과를 그대로 날짜 `k`에
라벨링하고 있었다. 실제로는 이 값이 **"k일까지의 데이터(k 자신의 수익률 포함)로 k+1일을
예측한 값"**이라 — 그날 자신의 등락폭이 이미 재료로 들어간, 명백한 미래정보 누수였다.

### 발견 경위

`가격예측_변동성_일일수집.py`(서빙용 "내일 예측" 함수) 작성 중, `forecast_next_day_sigma()`가
"오늘까지 데이터로 내일 예측"이 아니라 "이미 계산된 오늘 예측"과 동일한 값을 반환하는 것을
발견 → `arch`의 `forecast(start=k)` 의미를 재조사 → 수작업 GARCH 재귀식
(`σ²(t)=ω+αε²(t-1)+βσ²(t-1)`)과 실제 함수 출력을 위치별로 대조한 결과, 함수 출력이 "해석
A"(같은 위치)가 아니라 "해석 B"(한 칸 뒤 위치)와 소수점까지 정확히 일치함을 확인.

### 수정

`forecast_with_fixed_params()`가 원시 출력 행 i를 `start_pos+i+1` 날짜로 재라벨링하도록
수정(맨 마지막 값은 배열 밖 미래 시점이라 버림 — 서빙용은 `forecast_next_day_sigma()`가
별도로 이미 올바르게 처리). `fit_and_forecast_garch()`/`split_dataset.py`의 서빙 시퀀스
빌더도 이 변경에 맞춰 `start_pos`를 하나씩 당겨 호출하도록 동반 수정.

### 3중 독립 검증 (전부 실제값 대조, 코드 리뷰 아님)

1. **수동 재귀식 대조(005930)**: mu 보정 잔차로 손 계산한 σ가 수정된 함수 출력과 8자리까지
   완전 일치. 유일한 불일치(최대오차 0.27)는 계열 맨 앞 50개 날짜(2020-01 초, GARCH
   backcast 시딩 차이)에 국한 — train_end(2024-09-24)보다 4년 이상 앞이라 무관.
2. **다른 종목·다른 날짜 재확인**: 034730/2026-04-15(momentum·recent_vol_ma20·거시지표·
   target까지 전부), 051910/2026-06-01(GARCH σ만 별도) — 전부 원본 데이터부터 손으로
   재계산해 대조, 전부 일치.
3. **원본시퀀스 실험([7]) 착수 전 3종목 재확인**: 005930/2025-12-16, 105560/2026-04-02,
   035420/2026-07-15 — 20일 윈도우 전체(close_return/hl_range_ratio/open_gap_ratio/
   log_volume/garch_sigma)를 원본 OHLCV로 손 계산해 대조, 전부 일치, D 당일 값 섞임 없음.

(부수 발견: 거시지표(KOSPI 등)가 `build_stationary_features`의 사전 정렬 위에 프레임 전체가
한 번 더 shift(1)되어 최신값보다 하루 더 늦은 값을 쓰는 현상을 발견 — 재검토 결과 **리크는
아니고**(오히려 더 보수적) 2026-08-17 V2 설계 이후 계속 존재해온 특성으로, 오늘 새로 생긴
버그가 아니라 이미 안전한 것으로 판정됐던 사안임을 재확인했다. 최적화 여지는 있으나 이번
검증에서는 수정하지 않았다.)

---

## [4] 수정 후 재검증 결과

### GARCH(1,1) vs SMA20 (8종목, test n=236/종목)

| ticker | GARCH RMSE | GARCH MAE | SMA20 RMSE | SMA20 MAE | GARCH 승? |
|---|---|---|---|---|---|
| 005930 | 3.196002 | 2.399554 | 3.174026 | 2.332394 | 패 |
| 005380 | 3.191942 | 2.521502 | 3.125280 | 2.231593 | 패 |
| 051910 | 2.731912 | 2.105576 | 2.779425 | 2.073215 | 패 |
| 105560 | 1.863492 | 1.474358 | 1.805113 | 1.296545 | 패 |
| 207940 | 1.983879 | 1.524672 | 1.920853 | 1.295711 | 패 |
| 035420 | 2.521626 | 1.901033 | 2.628919 | 1.888449 | 패 |
| 034730 | 3.122351 | 2.339581 | 3.084722 | 2.272167 | 패 |
| 015760 | 2.403554 | 1.821128 | 2.461280 | 1.811533 | 패 |
| **평균** | **2.626845** | 2.010925 | **2.622452** | 1.900201 | **0/8** |

### 하이브리드(15피처: 14+GARCH σ) 재평가

| | RMSE | MAE |
|---|---|---|
| 순수 Transformer(14피처) | 2.865417 | 1.883791 |
| **하이브리드(15피처)** | **2.709781** | **1.833777** |
| GARCH(1,1) | 2.626845 | 2.010925 |
| SMA20 | 2.622452 | 1.900201 |

순수 Transformer 대비 개선(5.4%)은 있으나 **GARCH·SMA20 둘 다 못 이김**. 셔플(N=7) p=0.125
(이 N의 최솟값, 유의성 판정 불가 해상도).

### 정상/폭락 구간 분리 재확인 (005930 상세 + 8종목 요약)

| 구간 | GARCH RMSE | SMA20 RMSE | GARCH 승? |
|---|---|---|---|
| 평상시(115일) | 2.373 | 2.235 | 패 |
| 폭락구간(121일, 2026-02~07) | 3.817 | 3.860 | **승**(근소) |

8종목 요약: 평상시 승리 **0/8**, 폭락구간 승리 **4/8**(005930/051910/035420/015760) — "스트레스
구간에서 GARCH가 무너진다"는 가설과 **반대 방향**: GARCH는 β=0.85~0.93의 강한 지속성 때문에
평상시(변동 작음)에 오히려 SMA20보다 반응이 느려 손해를 본다.

### 조기경보 재검증 — 완전 붕괴

| | Recall | Precision | p-value |
|---|---|---|---|
| 버그 버전(1차 보고) | 84.6% | 72.6% | 0.001(유의) |
| **수정 후 재실행** | **0.7%** | 22.2% | **0.4186(유의 아님)** |

test 1,888건 중 모델 경보는 9건뿐(8종목 중 6종목 경보 0건). **조기경보 능력 자체가 버그로
만들어진 착시였음이 확정**됐다 — 2·3차(국면 진입 첫날, N 민감도) 재검증은 1차가 이미 우연
수준으로 무너져 실익이 없어 생략.

---

## [5] Parkinson 변동성 발견 — 현재까지 유일하게 검증된 개선

일중 고가-저가 범위 기반 Parkinson(1980) 추정량: `parkinson_vol(t) = sqrt(ln(high/low)²/(4ln2))×100`.

### 상관계수 (8종목 평균, test 구간, target=|당일 수익률|)

| | (a)당일 동시성(리크, 참고용) | (b)예측용(t-1까지) |
|---|---|---|
| Parkinson | 0.6418 | 0.2013 |
| GARCH σ | — | 0.2119 |
| SMA20 | — | 0.1683 |
| recent_vol_ma20 | — | 0.1679 |

### Parkinson-SMA20(20일 지연 이동평균) vs 기존 baseline (8종목 평균)

| | RMSE | MAE |
|---|---|---|
| **Parkinson-SMA20** | **2.5972** | **1.8773** |
| GARCH(1,1) | 2.6268 | 2.0109 |
| SMA20(종가기반) | 2.6225 | 1.9002 |

**GARCH·SMA20 둘 다(RMSE·MAE 모두) 이긴다** — 8종목 중 6종목에서 RMSE 기준으로도 SMA20보다
낫다. 이번 세션 전체에서 **유일하게 기존 baseline 둘 다를 실제로 넘어선 방법**이다.

---

## [6] Transformer가 이 신호를 못 씀

### SMA20을 16번째 피처로 추가 (recent_vol_ma20과 사실상 같은 정보임을 먼저 확인)

`recent_vol_ma20×100`과 GARCH baseline의 `SMA20`은 계산식(윈도우 20일, shift 정렬)이
동일하고 실측값도 ±1~2.4% 이내로 사실상 같은 값 — 즉 이 정보는 이미 15피처 하이브리드
안에 들어 있었다. 그런데도 SMA20 자체를 16번째 피처로 별도 추가해 재학습해도 개선되지
않았다(가설: 정규화가 항등매핑을 방해, 다른 피처들의 노이즈에 묻힘, garch_sigma와의 혼합
방식이 test에 일반화 안 됨).

### Parkinson-SMA20을 16번째 피처로 추가

중복도 확인(parkinson_ma20 vs recent_vol_ma20 상관 0.88, vs garch_sigma 0.65 — 0.95 미만,
"다른 정보"로 판단) 후 실제 재학습:

| | RMSE | MAE |
|---|---|---|
| 15피처 하이브리드 | 2.7098 | 1.8338 |
| **16피처(+parkinson_ma20)** | **2.7344** | **1.8356** |

**개선 없음, 오히려 악화**(8종목 중 6종목). GARCH·SMA20 대비도 개선 없음. 셔플(N=7) p=0.125.
**"단독 baseline으로는 이기는 정보라도 Transformer에 피처로 얹으면 못 쓴다"는 패턴이
SMA20에 이어 두 번째로 재현됐다.**

---

## [7] 원본 시퀀스 실험 — 압축 피처 제외해도 개선 안 됨

가설: "사람이 미리 압축한 통계(GARCH σ, SMA20 등)가 Transformer 고유의 시퀀스 패턴 학습을
방해했다." 검증: SMA20/recent_vol_ma20/Parkinson/momentum 등 압축 지속성 피처를 전부
빼고, `close_return/hl_range_ratio/open_gap_ratio/log_volume`(원본에 가까운 값) + GARCH σ
1개 + 거시지표 8개 + 종목 임베딩(13피처)만으로 재구성.

**사전 날짜매핑 검증(0단계, 실제값 대조)**: 8종목 중 3종목(005930/105560/035420)에서 각각
20일 윈도우 전체를 원본 OHLCV로 손 계산해 대조 — **전부 통과**, D 당일 값 섞임 없음, target·
GARCH σ 전부 일치.

### 결과 (8종목 평균)

| | RMSE | MAE |
|---|---|---|
| **원본시퀀스(13피처)** | **2.8397** | **1.8673** |
| 15피처 하이브리드 | 2.7098 | 1.8338 |
| GARCH(1,1) | 2.6268 | 2.0109 |
| SMA20 | 2.6225 | 1.9002 |
| Parkinson-SMA20 | 2.5972 | 1.8773 |

**8종목 전패 — 지금까지 시도한 모든 조합 중 가장 낮은 성능.** "압축 통계가 학습을
방해했다"는 가설은 **기각** — 오히려 반대로 원본에 가까운 값만 주니 더 나빠졌다.

---

## [8] 과적합 / 분산 붕괴 진단

### 학습 곡선 (MSELoss 기준)

**15피처 하이브리드** (best epoch=7):

| epoch | train_loss | val_loss |
|---|---|---|
| 1 | 2.2509 | 2.8243 |
| 3 | 2.1032 | 2.7908 |
| 7(best) | 2.0606 | 2.7789 |
| 15(조기종료) | 2.0421 | 2.8106 |

**13피처 원본시퀀스** (best epoch=12):

| epoch | train_loss | val_loss |
|---|---|---|
| 1 | 2.2511 | 2.8013 |
| 5 | 2.0971 | 2.7697 |
| 12(best) | 2.0507 | 2.7683 |
| 20(조기종료) | 2.0317 | 2.7722 |

train은 꾸준히(느리게) 감소, val은 epoch 3~7 근방에서 정체 — 1차 판정은 "과적합"이었다.

### train RMSE vs baseline TRAIN 성능 (in-sample)

| | train RMSE | train MAE | test RMSE | train→test 악화율 |
|---|---|---|---|---|
| 15피처 하이브리드 | 1.4182 | 0.9969 | 2.7820 | +96% |
| 13피처 원본시퀀스 | 1.4092 | 0.9974 | 2.9174 | +107% |
| GARCH(in-sample) | 1.6326 | 1.2901 | 2.6268 | +61% |
| SMA20(train) | 1.5654 | 1.0965 | 2.6225 | +68% |
| **"train 평균만 찍기"** | **1.478**(=√Var) | — | — | — |

모델이 GARCH·SMA20을 train에서 이기지만, **"train 평균만 찍기"(RMSE 1.478)조차 이미
GARCH·SMA20보다 낫다** — 모델의 실제 우위(1.418 vs 1.478)는 4%에 불과. 모델의 train→test
악화율(96~107%)도 baseline(61~68%)보다 커서 순수 레짐차이만으로는 설명 안 되는 부분이 있다.

### 분산 붕괴 확인 — 결정적 재진단

| 시점 | test 예측 mean | test 예측 std | 비고 |
|---|---|---|---|
| epoch0(무작위 초기화) | 0.2376 | 0.2270 | 노이즈 수준 |
| epoch1(1 epoch 학습) | 1.7856 | 0.2184 | — |
| **best_epoch(7)** | **1.8383** | **0.2608** | — |
| **실제 test target** | 2.7276 | **2.7453** | — |

- **best_epoch 예측 표준편차(0.26)가 실제 target 표준편차(2.75)의 9.5%** — 사실상 상수 찍기.
- epoch1↔best_epoch 예측 상관계수 **0.897** — 의미 있는 변화는 epoch 0→1 사이에서 다 끝남.
- epoch0(학습 전) loss=4.49/6.61 → **epoch1(1 epoch 후) loss=2.22/2.82로 이미 "train 평균만
  찍기" 수준(2.18)** — 첫 epoch 만에 대부분의 "학습"이 끝남.
- test에서 모델 MSE(7.953)는 "train 평균을 test에 그대로 찍기"(9.025)보다 겨우 12% 나을
  뿐이고, 그마저 대부분 "test 레짐이 더 변동성 크다"는 수준 정보(1.51→1.84로 예측 수준만
  이동)이지 날짜별 변화를 쫓아간 게 아니다.

**최종 재해석**: 정규화 과다로 인한 고전적 과적합(복잡한 train 패턴을 외워 test에서
못 씀)이 아니라, **MSE 손실이 약한 신호 아래에서 첫 epoch 만에 거의 상수(train 평균을 살짝
보정한 값)로 수렴해버리는 전형적 실패 패턴**이다. "train에서 baseline을 이긴다"는 것도
그 baseline들이 train에서는 평균-찍기보다도 못하다는 사실에 크게 기댄 것이라 증거력이 약함.

---

## [9] 다음 시도 후보 (미착수, 가설 단계)

- 분산 보존 손실 함수(예: MSE에 예측 분산 페널티 추가, 또는 quantile loss)
- 학습률/배치크기/모델 구조(d_model, 레이어 수, dropout) 재조정 — 지금 구조가 이 표본
  규모에 비해 최적인지 별도 검증 안 됨
- 분위수 회귀(quantile regression) — 변동성처럼 오른쪽 꼬리가 두꺼운 타겟에는 MSE 단일
  포인트 추정보다 분위수 예측이 나을 가능성
- 결정은 아직 하지 않았다 — 위는 선택지 나열이며 우선순위는 사람이 정함

---

## [10] 50종목 확장 — 표본 확대로 분산 붕괴 완화 시도

[8]의 분산 붕괴 진단 이후, "표본이 적어(8종목) 모델이 입력에 반응하는 법을 못 배운다"는
가설을 검증하기 위해 종목을 8→**50개**로 확장했다.

- `fdr.StockListing('KOSPI')`로 전체 KOSPI 종목 조회 → 종목명이 "우"/"우B"/"우C" 등으로
  끝나는 우선주 필터링(109개 제외) → 시가총액(`Marcap`) 상위 50개 선정
- 기존 9종목(활성 8 + SK하이닉스)이 전부 상위 50위 안에 이미 포함됨을 확인. 000660(SK
  하이닉스)도 이번엔 활성화(50종목 규모에서는 섹터 분산보다 표본 확대가 우선이라 판단)
- **종목명 오류 발견·정정**: 034730이 "현대건설"로 잘못 등록돼 있었음을 발견, 실제로는
  SK 주식회사(지주)임을 확인해 정정(위 상단 경고 박스 참고)
- 41개 신규 종목 OHLCV 적재(`주가_초기적재.py` 재사용, `STOCK_INITIAL_LOAD_START`부터).
  47개는 2020-01-02~2026-09-04 전체 커버, **3개는 상장/재상장일이 늦어 이력이 짧음**
  (LG에너지솔루션 2022-01-27~, SK스퀘어 2021-11-29~, HD현대중공업 2021-09-17~) — 셋 다
  val_end(2025-09-15)보다 훨씬 이전에 상장돼 **val/test는 50종목 전부 동일(237/236개)하고
  train만 자연스럽게 적게 확보됨**. `pooled_dataset.py`가 애초에 이 상황을 염두에 두고
  설계돼 있어(주석에 명시) 코드 수정 없이 정상 동작 확인(드라이런: train 52,838 / val
  11,850 / test 11,800, 에러 없음)
- 종목 임베딩 차원을 8 → **16**으로 확대(50종목 규모에서 8은 좁고, d_model=32 대비 임베딩이
  절반을 넘지 않도록 절충)

---

## [11] 50종목 결과 — 오늘 세션 유일의 통계적으로 유의한 개선

### 분산 붕괴 완화

| | 예측 std | target std | 비율 |
|---|---|---|---|
| 8종목(이전, [8]) | 0.2608 | 2.7453 | 9.5% |
| **50종목** | **0.9272** | 3.0110 | **30.8%** |

예측 범위도 0.29~4.09로 넓어짐(이전 1.00~2.45) — 완전히 해소되진 않았으나 뚜렷한 개선.

### baseline 비교 (50종목 평균)

| | RMSE | MAE |
|---|---|---|
| **하이브리드(50종목, 15피처)** | **2.7669** | **1.8985** |
| GARCH(1,1) | 2.8002 | 2.1061 |
| SMA20 | 2.7853 | 1.9984 |
| Parkinson-SMA20 | 2.7463 | 1.9674 |

GARCH·SMA20 대비 개선(RMSE·MAE 모두) = **True**. Parkinson-SMA20 대비는 근소하게 미달
(RMSE −0.7%, MAE는 오히려 +3.5% 앞섬 — 사실상 대등).

### 셔플 검증 — N=7 → N=30 확장

| | 셔플 평균±표준편차 | 실제값 | 격차(σ) | p-value |
|---|---|---|---|---|
| RMSE, N=7 | 3.1866±0.0097 | 2.8775 | 31.8σ | 0.1250(해상도 한계) |
| **RMSE, N=30** | 3.1875±0.0133 | 2.8775 | 23.3σ | **0.0323** |
| MAE, N=7 | 2.0124±0.0016 | 1.8985 | 69.6σ | 0.1250(해상도 한계) |
| **MAE, N=30** | 2.0124±0.0024 | 1.8985 | 47.7σ | **0.0323** |

30/30 셔플 전부 실제 모델보다 나쁨. N을 늘려도 격차(20~50σ 규모)가 무너지지 않고 견고하게
유지됨 — N=7에서의 p=0.125는 착시가 아니라 표본크기 해상도 한계였을 뿐이었고, N=30에서
**p<0.05로 통계적 유의성이 명확히 확인**됐다.

---

## 최종 상태 (2026-09-06 기준, 갱신)

**50종목 pooled 하이브리드 모델이 GARCH·SMA20 baseline을 통계적으로 유의하게 이겼다**
(N=30 셔플 검증, p=0.0323, 30/30 전부 실제 모델이 우세) — **오늘 세션에서 학습 기반
모델이 baseline을 유의하게 이긴 유일한 사례**다. 8종목 규모에서는 "첫 epoch 만에 거의
상수로 수렴하는 분산 붕괴"([8])로 실패했던 것이, 표본을 50종목으로 늘리자 분산 붕괴가
뚜렷이 완화되고(std 비율 9.5%→30.8%) baseline 개선까지 이어졌다.

**남은 과제**:
- (a) Parkinson-SMA20은 아직 근소하게 못 넘음(RMSE −0.7%, MAE는 오히려 +3.5% 앞섬 —
  사실상 대등한 수준)
- (b) 예측 분산이 target의 30.8%로, 완전히 해소된 것은 아님
- (c) 자동화 파이프라인(`가격예측_변동성_일일수집.py`)은 아직 미작성 — 8종목 시절 설계를
  50종목 구성으로 갱신해야 함
- (d) 배포 게이트(`passes_deployment_gate_volatility`)에 Parkinson-SMA20을 비교 대상으로
  포함시킬지 미결(현재는 GARCH·SMA20만 기준)

다음 세션 시작 시 할 일은 `CLAUDE.md`에 명시.
